
create or replace stream "LENDX_SANDBOX"."LENDX_STG".raw_loan_transactions_stream on table "LENDX_SANDBOX"."MAMBU_LENDX_SANDBOX_RAW"."LOAN_TRANSACTIONS";


CREATE OR REPLACE STREAM LENDX_SANDBOX.LENDX_STG.RAW_INSTALLMENTS_STREAM ON TABLE LENDX_SANDBOX.MAMBU_LENDX_SANDBOX_RAW.INSTALLMENTS;
CREATE OR REPLACE STREAM LENDX_SANDBOX.LENDX_STG.RAW_LOAN_REPAYMENTS_STREAM ON TABLE LENDX_SANDBOX.MAMBU_LENDX_SANDBOX_RAW.LOAN_REPAYMENTS;
CREATE OR REPLACE STREAM LENDX_SANDBOX.LENDX_STG.RAW_LOAN_REPAYMENTS_HISTORY_STREAM ON TABLE LENDX_SANDBOX.MAMBU_LENDX_SANDBOX_RAW.LOAN_REPAYMENTS;
CREATE OR REPLACE STREAM LENDX_SANDBOX.LENDX_STG.RAW_LOAN_ACCOUNTS_STREAM ON TABLE LENDX_SANDBOX.MAMBU_LENDX_SANDBOX_RAW.LOAN_ACCOUNTS;
CREATE OR REPLACE STREAM LENDX_SANDBOX.LENDX_STG.RAW_LOAN_PRODUCTS_STREAM ON TABLE MAMBU_LENDX_SANDBOX_RAW.LOAN_PRODUCTS;
CREATE OR REPLACE STREAM LENDX_SANDBOX.LENDX_STG.RAW_CLIENTS_STREAM ON TABLE LENDX_SANDBOX.MAMBU_LENDX_SANDBOX_RAW.CLIENTS;
CREATE OR REPLACE STREAM LENDX_SANDBOX.LENDX_STG.RAW_BRANCHES_STREAM ON TABLE LENDX_SANDBOX.MAMBU_LENDX_SANDBOX_RAW.BRANCHES;