-- Tasks by table pipeline have dependencies.
-- 1st. Executes STG then DW
-- Tree of tasks have to be in the same Schema.

--- RAW to STG -----

CREATE OR REPLACE TASK LENDX_SANDBOX.LENDX_DW.STG_ORIGINATOR
WAREHOUSE = COMPUTE_WH
schedule = '15 minute'
WHEN
system$stream_has_data('LENDX_SANDBOX.LENDX_STG.raw_branches_stream')
AS
INSERT INTO LENDX_SANDBOX.LENDX_STG.STG_ORIGINATOR
 (  DIMENSION_KEY,
    CREATION_DATE,
	EMAIL_ADDRESS,
	ENCODED_KEY,
	ID,
	LAST_MODIFIED_DATE,
	"NAME",
	NOTES,
	PHONE_NUMBER,
	STATE)
 SELECT	DISTINCT 
    MD5(ENCODED_KEY) AS DIMENSION_KEY,
 	CREATION_DATE,
	EMAIL_ADDRESS,
	ENCODED_KEY,
	ID,
	LAST_MODIFIED_DATE,
	"NAME",
	NOTES,
	PHONE_NUMBER,
	STATE
FROM LENDX_SANDBOX.LENDX_STG.raw_branches_stream
WHERE METADATA$ACTION IN ('INSERT','UPDATE');


CREATE OR REPLACE TASK LENDX_SANDBOX.LENDX_DW.STG_BORROWER
WAREHOUSE = COMPUTE_WH
AFTER LENDX_SANDBOX.LENDX_DW.DIM_ORIGINATOR
WHEN
system$stream_has_data('LENDX_SANDBOX.LENDX_STG.RAW_CLIENTS_STREAM')
AS
MERGE INTO LENDX_SANDBOX.LENDX_STG.STG_BORROWER AS tgt
USING LENDX_SANDBOX.LENDX_STG.RAW_CLIENTS_STREAM AS src
ON (tgt.ENCODED_KEY = src.ENCODED_KEY)
WHEN MATCHED AND METADATA$ACTION IN ( 'INSERT', 'UPDATE' ) THEN
    UPDATE SET tgt.ACTIVATION_DATE = src.ACTIVATION_DATE,
               tgt.CITY = src.ADDRESSES[0]:city::string,
               tgt.COUNTRY = src.ADDRESSES[0]:country::string,
               tgt.STREET_ADDRESS_LINE1 = src.ADDRESSES[0]:line1::string,
               tgt.STREET_ADDRESS_LINE2 = src.ADDRESSES[0]:line2::string,
               tgt.POST_CODE = src.ADDRESSES[0]:post_code::string,
               tgt.REGION = src.ADDRESSES[0]:region::string,
               tgt.BIRTH_DATE = src.BIRTH_DATE,
               tgt.APPROVED_DATE = src.APPROVED_DATE,
               tgt.CLIENT_ROLE_KEY = src.CLIENT_ROLE_KEY,
               tgt.EMAIL_ADDRESS = src.EMAIL_ADDRESS,
               tgt.FIRST_NAME = src.FIRST_NAME,
               tgt.GENDER = src.GENDER,
               tgt.GROUP_LOAN_CYCLE = src.GROUP_LOAN_CYCLE,               
               tgt.ID = src.ID,
               tgt.LAST_MODIFIED_DATE = src.LAST_MODIFIED_DATE,
               tgt.LAST_NAME = src.LAST_NAME,
               tgt.NOTES = src.NOTES,
               tgt.MIDDLE_NAME = src.MIDDLE_NAME,
               tgt.HOME_PHONE = src.HOME_PHONE,
               tgt.MOBILE_PHONE = src.MOBILE_PHONE,
               tgt.PREFERRED_LANGUAGE = src.PREFERRED_LANGUAGE,
               tgt.STATE = src.STATE,
			   tgt.ASSIGNED_ORIGINATOR_KEY = src.ASSIGNED_BRANCH_KEY
WHEN NOT MATCHED AND METADATA$ACTION IN ( 'INSERT', 'UPDATE' ) THEN
    INSERT
    (
        DIMENSION_KEY,
        ACTIVATION_DATE,
        CITY,
        COUNTRY,
        STREET_ADDRESS_LINE1,
        STREET_ADDRESS_LINE2,
        POST_CODE,
        REGION,
        BIRTH_DATE,
        APPROVED_DATE,
        CLIENT_ROLE_KEY,
        CREATION_DATE,
        EMAIL_ADDRESS,
        ENCODED_KEY,
        FIRST_NAME,
        GENDER,
        GROUP_LOAN_CYCLE,
        ID,
        LAST_MODIFIED_DATE,
        LAST_NAME,
        NOTES,
        MIDDLE_NAME,
        HOME_PHONE,
        MOBILE_PHONE,
        PREFERRED_LANGUAGE,
        STATE,
		ASSIGNED_ORIGINATOR_KEY
    )
    VALUES
    (MD5(src.ENCODED_KEY),
     src.ACTIVATION_DATE,
     ADDRESSES[0]:city::string,
     ADDRESSES[0]:country::string,
     ADDRESSES[0]:line1::string,
     ADDRESSES[0]:line2::string,
     ADDRESSES[0]:post_code::string,
     ADDRESSES[0]:region::string,
     src.BIRTH_DATE,
     src.APPROVED_DATE,
     src.CLIENT_ROLE_KEY,
     src.CREATION_DATE,
     src.EMAIL_ADDRESS,
     src.ENCODED_KEY,
     src.FIRST_NAME,
     src.GENDER,
     src.GROUP_LOAN_CYCLE,
     src.ID,
     src.LAST_MODIFIED_DATE,
     src.LAST_NAME,
     src.NOTES,
     src.MIDDLE_NAME,
     src.HOME_PHONE,
     src.MOBILE_PHONE,
     src.PREFERRED_LANGUAGE,
     src.STATE,
	 src.ASSIGNED_BRANCH_KEY
    );


CREATE OR REPLACE TASK LENDX_SANDBOX.LENDX_DW.STG_LOAN_PRODUCT
WAREHOUSE = COMPUTE_WH
AFTER LENDX_SANDBOX.LENDX_DW.DIM_BORROWER
WHEN
system$stream_has_data('LENDX_SANDBOX.LENDX_STG.RAW_LOAN_PRODUCTS_STREAM')
AS
MERGE INTO LENDX_SANDBOX.LENDX_STG.STG_LOAN_PRODUCT AS tgt
USING LENDX_SANDBOX.LENDX_STG.RAW_LOAN_PRODUCTS_STREAM AS src
ON (tgt.ENCODED_KEY = src.ENCODED_KEY)
WHEN MATCHED AND METADATA$ACTION IN ( 'INSERT', 'UPDATE' ) THEN
    UPDATE SET tgt.ACCOUNTING_METHOD = src.ACCOUNTING_METHOD,
               tgt.ACCOUNT_INITIAL_STATE = src.ACCOUNT_INITIAL_STATE,
               tgt.ACCOUNT_LINKING_ENABLED = src.ACCOUNT_LINKING_ENABLED,
               tgt.ACTIVATED = src.ACTIVATED,
               tgt.ALLOW_ARBITRARY_FEES = src.ALLOW_ARBITRARY_FEES,
               tgt.AMORTIZATION_METHOD = src.AMORTIZATION_METHOD,
               tgt.AUTO_CREATE_LINKED_ACCOUNTS = src.AUTO_CREATE_LINKED_ACCOUNTS,
               tgt.AUTO_LINK_ACCOUNTS = src.AUTO_LINK_ACCOUNTS,
               tgt.DAYS_IN_YEAR = src.DAYS_IN_YEAR,
               tgt.DEFAULT_LOAN_AMOUNT = src.DEFAULT_LOAN_AMOUNT,
               tgt.DEFAULT_PRINCIPAL_REPAYMENT_INTERVAL = src.DEFAULT_PRINCIPAL_REPAYMENT_INTERVAL,
               tgt.DEFAULT_REPAYMENT_PERIOD_COUNT = src.DEFAULT_REPAYMENT_PERIOD_COUNT,
               tgt.FOR_HYBRID_GROUPS = src.FOR_HYBRID_GROUPS,
               tgt.FOR_INDIVIDUALS = src.FOR_INDIVIDUALS,
               tgt.FOR_PURE_GROUPS = src.FOR_PURE_GROUPS,
               tgt.FUTURE_PAYMENTS_ACCEPTANCE = src.FUTURE_PAYMENTS_ACCEPTANCE,
               tgt.GRACE_PERIOD_TYPE = src.GRACE_PERIOD_TYPE,
               tgt.ID = src.ID,
               tgt.ID_GENERATOR_TYPE = src.ID_GENERATOR_TYPE,
               tgt.ID_PATTERN = src.ID_PATTERN,
               tgt.INTEREST_ACCRUED_ACCOUNTING_METHOD = src.INTEREST_ACCRUED_ACCOUNTING_METHOD,
               tgt.INTEREST_APPLICATION_METHOD = src.INTEREST_APPLICATION_METHOD,
               tgt.INTEREST_BALANCE_CALCULATION_METHOD = src.INTEREST_BALANCE_CALCULATION_METHOD,
               tgt.INTEREST_CALCULATION_METHOD = src.INTEREST_CALCULATION_METHOD,
               tgt.LAST_MODIFIED_DATE = src.LAST_MODIFIED_DATE,
               tgt.LATE_PAYMENTS_RECALCULATION_METHOD = src.LATE_PAYMENTS_RECALCULATION_METHOD,
               tgt.LINE_OF_CREDIT_REQUIREMENT = src.LINE_OF_CREDIT_REQUIREMENT,
               tgt.LOAN_FEES = src.LOAN_FEES,
               tgt.LOAN_PENALTY_CALCULATION_METHOD = src.LOAN_PENALTY_CALCULATION_METHOD,
               tgt.LOAN_PRODUCT_RULES = src.LOAN_PRODUCT_RULES,
               tgt.LOAN_PRODUCT_TYPE = src.LOAN_PRODUCT_TYPE,
               tgt.MAX_NUMBER_OF_DISBURSEMENT_TRANCHES = src.MAX_NUMBER_OF_DISBURSEMENT_TRANCHES,
               tgt.PAYMENT_METHOD = src.PAYMENT_METHOD,
               tgt.PREPAYMENT_ACCEPTANCE = src.PREPAYMENT_ACCEPTANCE,
               tgt.PRODUCT_DESCRIPTION = src.PRODUCT_DESCRIPTION,
               tgt.PRODUCT_NAME = src.PRODUCT_NAME,
               tgt.REPAYMENT_ALLOCATION_ORDER = src.REPAYMENT_ALLOCATION_ORDER,
               tgt.REPAYMENT_CURRENCY_ROUNDING = src.REPAYMENT_CURRENCY_ROUNDING,
               tgt.REPAYMENT_ELEMENTS_ROUNDING_METHOD = src.REPAYMENT_ELEMENTS_ROUNDING_METHOD,
               tgt.REPAYMENT_PERIOD_UNIT = src.REPAYMENT_PERIOD_UNIT,
               tgt.REPAYMENT_RESCHEDULING_METHOD = src.REPAYMENT_RESCHEDULING_METHOD,
               tgt.REPAYMENT_SCHEDULE_EDIT_OPTIONS = src.REPAYMENT_SCHEDULE_EDIT_OPTIONS,
               tgt.REPAYMENT_SCHEDULE_METHOD = src.REPAYMENT_SCHEDULE_METHOD,
               tgt.ROUNDING_REPAYMENT_SCHEDULE_METHOD = src.ROUNDING_REPAYMENT_SCHEDULE_METHOD,
               tgt.SCHEDULE_DUE_DATES_METHOD = src.SCHEDULE_DUE_DATES_METHOD,
               tgt.SCHEDULE_INTEREST_DAYS_COUNT_METHOD = src.SCHEDULE_INTEREST_DAYS_COUNT_METHOD,
               tgt.SETTLEMENT_OPTIONS = src.SETTLEMENT_OPTIONS,
               tgt.TAXES_ON_FEES_ENABLED = src.TAXES_ON_FEES_ENABLED,
               tgt.TAXES_ON_INTEREST_ENABLED = src.TAXES_ON_INTEREST_ENABLED,
               tgt.TAXES_ON_PENALTY_ENABLED = src.TAXES_ON_PENALTY_ENABLED,
               tgt.APPLY_INTEREST_ON_PREPAYMENT_METHOD = src.APPLY_INTEREST_ON_PREPAYMENT_METHOD,
               tgt.INTEREST_RATE_ENCODED_KEY = src.INTEREST_RATE_SETTINGS:encoded_key::string,
			   tgt.DEFAULT_INTEREST_RATE = src.INTEREST_RATE_SETTINGS:default_interest_rate::number,
               tgt.INTEREST_CHARGE_FREQUENCY = src.INTEREST_RATE_SETTINGS:interest_charge_frequency::string,
               tgt.INTEREST_CHARGE_FREQUENCY_COUNT = src.INTEREST_RATE_SETTINGS:interest_charge_frequency_count::string,
               tgt.INTEREST_RATE_SOURCE = src.INTEREST_RATE_SETTINGS:interest_rate_source::string,
               tgt.INTEREST_RATE_TERMS = src.INTEREST_RATE_SETTINGS:interest_rate_terms::string,
               tgt.PRODUCT_SECURITY_ENCODED_KEY = src.PRODUCT_SECURITY_SETTINGS:encoded_key::varchar,
               tgt.PRODUCT_SECURITY_IS_COLLATERAL_ENABLED = src.PRODUCT_SECURITY_SETTINGS:is_collateral_enabled::boolean,
               tgt.PRODUCT_SECURITY_IS_GUARANTORS_ENABLED = src.PRODUCT_SECURITY_SETTINGS:is_guarantors_enabled::boolean,
               tgt.PRODUCT_SECURITY_IS_INVESTOR_FUNDS_ENABLED = src.PRODUCT_SECURITY_SETTINGS:is_investor_funds_enabled::boolean,
               tgt.PRODUCT_SECURITY_REQUIRED_GUARANTIES = src.PRODUCT_SECURITY_SETTINGS:required_guaranties::number
WHEN NOT MATCHED AND METADATA$ACTION IN ( 'INSERT', 'UPDATE' ) THEN
    INSERT
    (
        DIMENSION_KEY,
        ACCOUNTING_METHOD,
        ACCOUNT_INITIAL_STATE,
        ACCOUNT_LINKING_ENABLED,
        ACTIVATED,
        ALLOW_ARBITRARY_FEES,
        AMORTIZATION_METHOD,
        AUTO_CREATE_LINKED_ACCOUNTS,
        AUTO_LINK_ACCOUNTS,
        CREATION_DATE,
        DAYS_IN_YEAR,
        DEFAULT_LOAN_AMOUNT,
        DEFAULT_PRINCIPAL_REPAYMENT_INTERVAL,
        DEFAULT_REPAYMENT_PERIOD_COUNT,
        ENCODED_KEY,
        FOR_HYBRID_GROUPS,
        FOR_INDIVIDUALS,
        FOR_PURE_GROUPS,
        FUTURE_PAYMENTS_ACCEPTANCE,
        GRACE_PERIOD_TYPE,
        ID,
        ID_GENERATOR_TYPE,
        ID_PATTERN,
        INTEREST_ACCRUED_ACCOUNTING_METHOD,
        INTEREST_APPLICATION_METHOD,
        INTEREST_BALANCE_CALCULATION_METHOD,
        INTEREST_CALCULATION_METHOD,
        LAST_MODIFIED_DATE,
        LATE_PAYMENTS_RECALCULATION_METHOD,
        LINE_OF_CREDIT_REQUIREMENT,
        LOAN_FEES,
        LOAN_PENALTY_CALCULATION_METHOD,
        LOAN_PRODUCT_RULES,
        LOAN_PRODUCT_TYPE,
        MAX_NUMBER_OF_DISBURSEMENT_TRANCHES,
        PAYMENT_METHOD,
        PREPAYMENT_ACCEPTANCE,
        PRODUCT_DESCRIPTION,
        PRODUCT_NAME,
        REPAYMENT_ALLOCATION_ORDER,
        REPAYMENT_CURRENCY_ROUNDING,
        REPAYMENT_ELEMENTS_ROUNDING_METHOD,
        REPAYMENT_PERIOD_UNIT,
        REPAYMENT_RESCHEDULING_METHOD,
        REPAYMENT_SCHEDULE_EDIT_OPTIONS,
        REPAYMENT_SCHEDULE_METHOD,
        ROUNDING_REPAYMENT_SCHEDULE_METHOD,
        SCHEDULE_DUE_DATES_METHOD,
        SCHEDULE_INTEREST_DAYS_COUNT_METHOD,
        SETTLEMENT_OPTIONS,
        TAXES_ON_FEES_ENABLED,
        TAXES_ON_INTEREST_ENABLED,
        TAXES_ON_PENALTY_ENABLED,
        APPLY_INTEREST_ON_PREPAYMENT_METHOD,
        INTEREST_RATE_ENCODED_KEY,
		DEFAULT_INTEREST_RATE,
        INTEREST_CHARGE_FREQUENCY,
        INTEREST_CHARGE_FREQUENCY_COUNT,
        INTEREST_RATE_SOURCE,
        INTEREST_RATE_TERMS,
        PRODUCT_SECURITY_ENCODED_KEY,
        PRODUCT_SECURITY_IS_COLLATERAL_ENABLED,
        PRODUCT_SECURITY_IS_GUARANTORS_ENABLED,
        PRODUCT_SECURITY_IS_INVESTOR_FUNDS_ENABLED,
        PRODUCT_SECURITY_REQUIRED_GUARANTIES
    )
    VALUES
    (MD5(src.ENCODED_KEY),
     src.ACCOUNTING_METHOD,
     src.ACCOUNT_INITIAL_STATE,
     src.ACCOUNT_LINKING_ENABLED,
     src.ACTIVATED,
     src.ALLOW_ARBITRARY_FEES,
     src.AMORTIZATION_METHOD,
     src.AUTO_CREATE_LINKED_ACCOUNTS,
     src.AUTO_LINK_ACCOUNTS,
     src.CREATION_DATE,
     src.DAYS_IN_YEAR,
     src.DEFAULT_LOAN_AMOUNT,
     src.DEFAULT_PRINCIPAL_REPAYMENT_INTERVAL,
     src.DEFAULT_REPAYMENT_PERIOD_COUNT,
     src.ENCODED_KEY,
     src.FOR_HYBRID_GROUPS,
     src.FOR_INDIVIDUALS,
     src.FOR_PURE_GROUPS,
     src.FUTURE_PAYMENTS_ACCEPTANCE,
     src.GRACE_PERIOD_TYPE,
     src.ID,
     src.ID_GENERATOR_TYPE,
     src.ID_PATTERN,
     src.INTEREST_ACCRUED_ACCOUNTING_METHOD,
     src.INTEREST_APPLICATION_METHOD,
     src.INTEREST_BALANCE_CALCULATION_METHOD,
     src.INTEREST_CALCULATION_METHOD,
     src.LAST_MODIFIED_DATE,
     src.LATE_PAYMENTS_RECALCULATION_METHOD,
     src.LINE_OF_CREDIT_REQUIREMENT,
     src.LOAN_FEES,
     src.LOAN_PENALTY_CALCULATION_METHOD,
     src.LOAN_PRODUCT_RULES,
     src.LOAN_PRODUCT_TYPE,
     src.MAX_NUMBER_OF_DISBURSEMENT_TRANCHES,
     src.PAYMENT_METHOD,
     src.PREPAYMENT_ACCEPTANCE,
     src.PRODUCT_DESCRIPTION,
     src.PRODUCT_NAME,
     src.REPAYMENT_ALLOCATION_ORDER,
     src.REPAYMENT_CURRENCY_ROUNDING,
     src.REPAYMENT_ELEMENTS_ROUNDING_METHOD,
     src.REPAYMENT_PERIOD_UNIT,
     src.REPAYMENT_RESCHEDULING_METHOD,
     src.REPAYMENT_SCHEDULE_EDIT_OPTIONS,
     src.REPAYMENT_SCHEDULE_METHOD,
     src.ROUNDING_REPAYMENT_SCHEDULE_METHOD,
     src.SCHEDULE_DUE_DATES_METHOD,
     src.SCHEDULE_INTEREST_DAYS_COUNT_METHOD,
     src.SETTLEMENT_OPTIONS,
     src.TAXES_ON_FEES_ENABLED,
     src.TAXES_ON_INTEREST_ENABLED,
     src.TAXES_ON_PENALTY_ENABLED,
     src.APPLY_INTEREST_ON_PREPAYMENT_METHOD,     
     src.INTEREST_RATE_SETTINGS:encoded_key::string,
	 src.INTEREST_RATE_SETTINGS:default_interest_rate::number,
     src.INTEREST_RATE_SETTINGS:interest_charge_frequency::string,
     src.INTEREST_RATE_SETTINGS:interest_charge_frequency_count::string,
     src.INTEREST_RATE_SETTINGS:interest_rate_source::string,
     src.INTEREST_RATE_SETTINGS:interest_rate_terms::string,
     src.PRODUCT_SECURITY_SETTINGS:encoded_key::varchar,
     src.PRODUCT_SECURITY_SETTINGS:is_collateral_enabled::boolean,
     src.PRODUCT_SECURITY_SETTINGS:is_guarantors_enabled::boolean,
     src.PRODUCT_SECURITY_SETTINGS:is_investor_funds_enabled::boolean,
     src.PRODUCT_SECURITY_SETTINGS:required_guaranties::number
    );


CREATE OR REPLACE TASK LENDX_SANDBOX.LENDX_DW.STG_LOAN_ACCOUNTS
WAREHOUSE = COMPUTE_WH
AFTER LENDX_SANDBOX.LENDX_DW.DIM_LOAN_PRODUCT
WHEN
system$stream_has_data('LENDX_SANDBOX.LENDX_STG.RAW_LOAN_ACCOUNTS_STREAM')
AS
MERGE INTO LENDX_SANDBOX.LENDX_STG.STG_LOAN_ACCOUNTS AS tgt
USING LENDX_SANDBOX.LENDX_STG.RAW_LOAN_ACCOUNTS_STREAM AS src
ON (
       tgt.ASSIGNED_BRANCH_KEY = src.ASSIGNED_BRANCH_KEY
       AND tgt.PRODUCT_TYPE_KEY = src.PRODUCT_TYPE_KEY
       AND tgt.ACCOUNT_HOLDER_KEY = src.ACCOUNT_HOLDER_KEY
       AND tgt.ENCODED_KEY = src.ENCODED_KEY
   )
WHEN MATCHED AND METADATA$ACTION IN ( 'INSERT', 'UPDATE' ) THEN
    UPDATE SET tgt.DIM_TIME_APPROVED = TO_NUMBER(TO_CHAR(src.APPROVED_DATE,'YYYYMMDD')),
			   tgt.ACCOUNT_ARREARS_DATE_CALCULATION_METHOD = src.ACCOUNT_ARREARS_SETTINGS:date_calculation_method::varchar,
               tgt.ACCOUNT_ARREARS_ENCODED_KEY = src.ACCOUNT_ARREARS_SETTINGS:encoded_key::varchar,
               tgt.ACCOUNT_ARREARS_NON_WORKING_DAYS_METHOD = src.ACCOUNT_ARREARS_SETTINGS:non_working_days_method::varchar,
               tgt.ACCOUNT_ARREARS_TOLERANCE_CALCULATION_METHOD = src.ACCOUNT_ARREARS_SETTINGS:tolerance_calculation_method::varchar,
               tgt.ACCOUNT_ARREARS_TOLERANCE_PERIOD = src.ACCOUNT_ARREARS_SETTINGS:tolerance_period::number,
               tgt.ACCOUNT_HOLDER_TYPE = src.ACCOUNT_HOLDER_TYPE,
               tgt.ACCOUNT_STATE = src.ACCOUNT_STATE,
               tgt.ACCOUNT_SUB_STATE = src.ACCOUNT_SUB_STATE,
               tgt.ACCRUED_INTEREST = src.ACCRUED_INTEREST,
               tgt.ACCRUED_PENALTY = src.ACCRUED_PENALTY,
               tgt.ACTIVATION_TRANSACTION_KEY = src.ACTIVATION_TRANSACTION_KEY,
               tgt.ALLOW_OFFSET = src.ALLOW_OFFSET,
               tgt.APPROVED_DATE = src.APPROVED_DATE,
               tgt.ARREARS_TOLERANCE_PERIOD = src.ARREARS_TOLERANCE_PERIOD,
               tgt.ASSETS = src.ASSETS,             
			   tgt.FEES_BALANCE = src.BALANCES:fees_balance::number,
               tgt.FEES_DUE = src.BALANCES:fees_due::number,
               tgt.FEES_PAID = src.BALANCES:fees_paid::number,
               tgt.INTEREST_BALANCE = src.BALANCES:interest_balance::number,
               tgt.INTEREST_DUE = src.BALANCES:interest_due::number,
               tgt.INTEREST_FROM_ARREARS_BALANCE = src.BALANCES:interest_from_arrears_balance::number,
               tgt.INTEREST_FROM_ARREARS_DUE = src.BALANCES:interest_from_arrears_due::number,
               tgt.INTEREST_FROM_ARREARS_PAID = src.BALANCES:interest_from_arrears_paid::number,
               tgt.INTEREST_PAID = src.BALANCES:interest_paid::number,
               tgt.PENALTY_BALANCE = src.BALANCES:penalty_balance::number,
               tgt.PENALTY_DUE = src.BALANCES:penalty_due::number,
               tgt.PENALTY_PAID = src.BALANCES:penalty_paid::number,
               tgt.PRINCIPAL_BALANCE = src.BALANCES:principal_balance::number,
               tgt.PRINCIPAL_DUE = src.BALANCES:principal_due::number,
               tgt.PRINCIPAL_PAID = src.BALANCES:principal_paid::number,
               tgt.REDRAW_BALANCE = src.BALANCES:redraw_balance::number,
               tgt.CLOSED_DATE = src.CLOSED_DATE,
               tgt.CUSTOM_FIELDS = src.CUSTOM_FIELDS,
               tgt.DISBURSEMENT_DATE = src.DISBURSEMENT_DETAILS:disbursement_date::date,
               tgt.EXPECTED_DISBURSEMENT_DATE = src.DISBURSEMENT_DETAILS:expected_disbursement_date::date,
               tgt.FIRST_REPAYMENT_DATE = src.DISBURSEMENT_DETAILS:first_repayment_date::date,
               tgt.FUNDING_SOURCES = src.FUNDING_SOURCES,
               tgt.FUTURE_PAYMENTS_ACCEPTANCE = src.FUTURE_PAYMENTS_ACCEPTANCE,
               tgt.GUARANTORS = src.GUARANTORS,
               tgt.ID = src.ID,
               tgt.INTEREST_FROM_ARREARS_ACCRUED = src.INTEREST_FROM_ARREARS_ACCRUED,
               tgt.ACCRUE_INTEREST_AFTER_MATURITY = src.INTEREST_SETTINGS:accrue_interest_after_maturity::boolean,
               tgt.INTEREST_APPLICATION_METHOD = src.INTEREST_SETTINGS:interest_application_method::varchar,
               tgt.INTEREST_BALANCE_CALCULATION_METHOD = src.INTEREST_SETTINGS:interest_balance_calculation_method::varchar,
               tgt.INTEREST_CALCULATION_METHOD = src.INTEREST_SETTINGS:interest_calculation_method::varchar,
               tgt.INTEREST_CHARGE_FREQUENCY = src.INTEREST_SETTINGS:interest_charge_frequency::varchar,
               tgt.INTEREST_RATE = src.INTEREST_SETTINGS:interest_rate::number,
               tgt.INTEREST_RATE_SOURCE = src.INTEREST_SETTINGS:interest_rate_source::varchar,
               tgt.INTEREST_TYPE = src.INTEREST_SETTINGS:interest_type::varchar,
               tgt.LAST_ACCOUNT_APPRAISAL_DATE = src.LAST_ACCOUNT_APPRAISAL_DATE,
               tgt.LAST_INTEREST_APPLIED_DATE = src.LAST_INTEREST_APPLIED_DATE,
               tgt.LAST_MODIFIED_DATE = src.LAST_MODIFIED_DATE,
               tgt.LAST_SET_TO_ARREARS_DATE = src.LAST_SET_TO_ARREARS_DATE,
               tgt.LATE_PAYMENTS_RECALCULATION_METHOD = src.LATE_PAYMENTS_RECALCULATION_METHOD,
               tgt.LOAN_AMOUNT = src.LOAN_AMOUNT,
               tgt.LOAN_NAME = src.LOAN_NAME,
               tgt.ORIGINAL_ACCOUNT_KEY = src.ORIGINAL_ACCOUNT_KEY,
               tgt.PAYMENT_METHOD = src.PAYMENT_METHOD,
               tgt.LOAN_PENALTY_CALCULATION_METHOD = src.PENALTY_SETTINGS:loan_penalty_calculation_method::varchar,
               tgt.PENALTY_RATE = src.PENALTY_SETTINGS:penalty_rate::number,
               tgt.APPLY_INTEREST_ON_PREPAYMENT_METHOD = src.PREPAYMENT_SETTINGS:apply_interest_on_prepayment_method::varchar,
               tgt.PREPAYMENT_RECALCULATION_METHOD = src.PREPAYMENT_SETTINGS:prepayment_recalculation_method::varchar,
               tgt.RESCHEDULED_ACCOUNT_KEY = src.RESCHEDULED_ACCOUNT_KEY,
               tgt.GRACE_PERIOD = src.SCHEDULE_SETTINGS:grace_period::number,
               tgt.GRACE_PERIOD_TYPE = src.SCHEDULE_SETTINGS:grace_period_type::varchar,
               tgt.HAS_CUSTOM_SCHEDULE = src.SCHEDULE_SETTINGS:has_custom_schedule::boolean,
               tgt.PAYMENT_PLAN = src.SCHEDULE_SETTINGS:payment_plan::variant,
               tgt.PERIODIC_PAYMENT = src.SCHEDULE_SETTINGS:periodic_payment::number,
               tgt.PRINCIPAL_REPAYMENT_INTERVAL = src.SCHEDULE_SETTINGS:principal_repayment_interval::number,
               tgt.REPAYMENT_INSTALLMENTS = src.SCHEDULE_SETTINGS:repayment_installments::number,
               tgt.REPAYMENT_PERIOD_COUNT = src.SCHEDULE_SETTINGS:repayment_period_count::number,
               tgt.REPAYMENT_PERIOD_UNIT = src.SCHEDULE_SETTINGS:repayment_period_unit::varchar,
               tgt.REPAYMENT_SCHEDULE_METHOD = src.SCHEDULE_SETTINGS:repayment_schedule_method::varchar,
               tgt.SCHEDULE_DUE_DATES_METHOD = src.SCHEDULE_SETTINGS:schedule_due_dates_method::varchar,
               tgt.TRANCHES = src.TRANCHES,
               tgt.LAST_INTEREST_REVIEW_DATE = src.LAST_INTEREST_REVIEW_DATE,
               tgt.CURRENCY_CODE = src.CURRENCY:code:varchar
WHEN NOT MATCHED AND METADATA$ACTION IN ( 'INSERT', 'UPDATE' ) THEN
    INSERT
    (	FACT_KEY,
        DIM_ORIGINATOR,
        DIM_LOAN_PRODUCT,
        DIM_BORROWER,
        ENCODED_KEY,
		DIM_TIME_APPROVED,
        ACCOUNT_ARREARS_DATE_CALCULATION_METHOD,
        ACCOUNT_ARREARS_ENCODED_KEY,
        ACCOUNT_ARREARS_NON_WORKING_DAYS_METHOD,
        ACCOUNT_ARREARS_TOLERANCE_CALCULATION_METHOD,
        ACCOUNT_ARREARS_TOLERANCE_PERIOD,
        ACCOUNT_HOLDER_KEY,
        ACCOUNT_HOLDER_TYPE,
        ACCOUNT_STATE,
        ACCOUNT_SUB_STATE,
        ACCRUED_INTEREST,
        ACCRUED_PENALTY,
        ACTIVATION_TRANSACTION_KEY,
        ALLOW_OFFSET,
        APPROVED_DATE,
        ARREARS_TOLERANCE_PERIOD,
        ASSETS,
        ASSIGNED_BRANCH_KEY,
        FEES_BALANCE,
        FEES_DUE,
        FEES_PAID,
        INTEREST_BALANCE,
        INTEREST_DUE,
        INTEREST_FROM_ARREARS_BALANCE,
        INTEREST_FROM_ARREARS_DUE,
        INTEREST_FROM_ARREARS_PAID,
        INTEREST_PAID,
        PENALTY_BALANCE,
        PENALTY_DUE,
        PENALTY_PAID,
        PRINCIPAL_BALANCE,
        PRINCIPAL_DUE,
        PRINCIPAL_PAID,
        REDRAW_BALANCE,
        CLOSED_DATE,
        CREATION_DATE,
        CUSTOM_FIELDS,
        DISBURSEMENT_DATE,
        EXPECTED_DISBURSEMENT_DATE,
        FIRST_REPAYMENT_DATE,
        FUNDING_SOURCES,
        FUTURE_PAYMENTS_ACCEPTANCE,
        GUARANTORS,
        ID,
        INTEREST_FROM_ARREARS_ACCRUED,
        ACCRUE_INTEREST_AFTER_MATURITY,
        INTEREST_APPLICATION_METHOD,
        INTEREST_BALANCE_CALCULATION_METHOD,
        INTEREST_CALCULATION_METHOD,
        INTEREST_CHARGE_FREQUENCY,
        INTEREST_RATE,
        INTEREST_RATE_SOURCE,
        INTEREST_TYPE,
        LAST_ACCOUNT_APPRAISAL_DATE,
        LAST_INTEREST_APPLIED_DATE,
        LAST_MODIFIED_DATE,
        LAST_SET_TO_ARREARS_DATE,
        LATE_PAYMENTS_RECALCULATION_METHOD,
        LOAN_AMOUNT,
        LOAN_NAME,
        ORIGINAL_ACCOUNT_KEY,
        PAYMENT_METHOD,
        LOAN_PENALTY_CALCULATION_METHOD,
        PENALTY_RATE,
        APPLY_INTEREST_ON_PREPAYMENT_METHOD,
        PREPAYMENT_RECALCULATION_METHOD,
        PRODUCT_TYPE_KEY,
        RESCHEDULED_ACCOUNT_KEY,
        GRACE_PERIOD,
        GRACE_PERIOD_TYPE,
        HAS_CUSTOM_SCHEDULE,
        PAYMENT_PLAN,
        PERIODIC_PAYMENT,
        PRINCIPAL_REPAYMENT_INTERVAL,
        REPAYMENT_INSTALLMENTS,
        REPAYMENT_PERIOD_COUNT,
        REPAYMENT_PERIOD_UNIT,
        REPAYMENT_SCHEDULE_METHOD,
        SCHEDULE_DUE_DATES_METHOD,
        TRANCHES,
        LAST_INTEREST_REVIEW_DATE,
        CURRENCY_CODE
    )
    VALUES
    (MD5(src.ENCODED_KEY),	
	 LENDX_SANDBOX.LENDX_DW.GET_ORIGINATOR_KEY(ASSIGNED_BRANCH_KEY),
     LENDX_SANDBOX.LENDX_DW.GET_LOAN_PRODUCT_KEY(PRODUCT_TYPE_KEY),
     LENDX_SANDBOX.LENDX_DW.GET_BORROWER_KEY(ACCOUNT_HOLDER_KEY),
     src.ENCODED_KEY,
	 COALESCE(TO_NUMBER(TO_CHAR(src.APPROVED_DATE,'YYYYMMDD')), 10000101),
     src.ACCOUNT_ARREARS_SETTINGS:date_calculation_method::varchar,
     src.ACCOUNT_ARREARS_SETTINGS:encoded_key::varchar,
     src.ACCOUNT_ARREARS_SETTINGS:non_working_days_method::varchar,
     src.ACCOUNT_ARREARS_SETTINGS:tolerance_calculation_method::varchar,
     src.ACCOUNT_ARREARS_SETTINGS:tolerance_period::number,
     src.ACCOUNT_HOLDER_KEY,
     src.ACCOUNT_HOLDER_TYPE,
     src.ACCOUNT_STATE,
     src.ACCOUNT_SUB_STATE,
     src.ACCRUED_INTEREST,
     src.ACCRUED_PENALTY,
     src.ACTIVATION_TRANSACTION_KEY,
     src.ALLOW_OFFSET,
     src.APPROVED_DATE,
     src.ARREARS_TOLERANCE_PERIOD,
     src.ASSETS,
     src.ASSIGNED_BRANCH_KEY,
     src.BALANCES:fees_balance::number,
     src.BALANCES:fees_due::number,
     src.BALANCES:fees_paid::number,
     src.BALANCES:interest_balance::number,
     src.BALANCES:interest_due::number,
     src.BALANCES:interest_from_arrears_balance::number,
     src.BALANCES:interest_from_arrears_due::number,
     src.BALANCES:interest_from_arrears_paid::number,
     src.BALANCES:interest_paid::number,
     src.BALANCES:penalty_balance::number,
     src.BALANCES:penalty_due::number,
     src.BALANCES:penalty_paid::number,
     src.BALANCES:principal_balance::number,
     src.BALANCES:principal_due::number,
     src.BALANCES:principal_paid::number,
     src.BALANCES:redraw_balance::number,
     src.CLOSED_DATE,
     src.CREATION_DATE,
     src.CUSTOM_FIELDS,
     src.DISBURSEMENT_DETAILS:disbursement_date::date,
     src.DISBURSEMENT_DETAILS:expected_disbursement_date::date,
     src.DISBURSEMENT_DETAILS:first_repayment_date::date,
     src.FUNDING_SOURCES,
     src.FUTURE_PAYMENTS_ACCEPTANCE,
     src.GUARANTORS,
     src.ID,
     src.INTEREST_FROM_ARREARS_ACCRUED,
     src.INTEREST_SETTINGS:accrue_interest_after_maturity::boolean,
     src.INTEREST_SETTINGS:interest_application_method::varchar,
     src.INTEREST_SETTINGS:interest_balance_calculation_method::varchar,
     src.INTEREST_SETTINGS:interest_calculation_method::varchar,
     src.INTEREST_SETTINGS:interest_charge_frequency::varchar,
     src.INTEREST_SETTINGS:interest_rate::number,
     src.INTEREST_SETTINGS:interest_rate_source::varchar,
     src.INTEREST_SETTINGS:interest_type::varchar,
     src.LAST_ACCOUNT_APPRAISAL_DATE,
     src.LAST_INTEREST_APPLIED_DATE,
     src.LAST_MODIFIED_DATE,
     src.LAST_SET_TO_ARREARS_DATE,
     src.LATE_PAYMENTS_RECALCULATION_METHOD,
     src.LOAN_AMOUNT,
     src.LOAN_NAME,
     src.ORIGINAL_ACCOUNT_KEY,
     src.PAYMENT_METHOD,
     src.PENALTY_SETTINGS:loan_penalty_calculation_method::varchar,
     src.PENALTY_SETTINGS:penalty_rate::number,
     src.PREPAYMENT_SETTINGS:apply_interest_on_prepayment_method::varchar,
     src.PREPAYMENT_SETTINGS:prepayment_recalculation_method::varchar,
     src.PRODUCT_TYPE_KEY,
     src.RESCHEDULED_ACCOUNT_KEY,
     src.SCHEDULE_SETTINGS:grace_period::number,
     src.SCHEDULE_SETTINGS:grace_period_type::varchar,
     src.SCHEDULE_SETTINGS:has_custom_schedule::boolean,
     src.SCHEDULE_SETTINGS:payment_plan::variant,
     src.SCHEDULE_SETTINGS:periodic_payment::number,
     src.SCHEDULE_SETTINGS:principal_repayment_interval::number,
     src.SCHEDULE_SETTINGS:repayment_installments::number,
     src.SCHEDULE_SETTINGS:repayment_period_count::number,
     src.SCHEDULE_SETTINGS:repayment_period_unit::varchar,
     src.SCHEDULE_SETTINGS:repayment_schedule_method::varchar,
     src.SCHEDULE_SETTINGS:schedule_due_dates_method::varchar,
     src.TRANCHES,
     src.LAST_INTEREST_REVIEW_DATE,
     src.CURRENCY:code:varchar
    );


CREATE OR REPLACE TASK LENDX_SANDBOX.LENDX_DW.STG_LOAN_REPAYMENTS
WAREHOUSE = COMPUTE_WH
AFTER LENDX_SANDBOX.LENDX_DW.FACT_LOAN_ACCOUNTS
WHEN
system$stream_has_data('LENDX_SANDBOX.LENDX_STG.RAW_LOAN_REPAYMENTS_STREAM')
AS
MERGE INTO LENDX_SANDBOX.LENDX_STG.STG_LOAN_REPAYMENTS AS tgt
USING LENDX_SANDBOX.LENDX_STG.RAW_LOAN_REPAYMENTS_STREAM AS src
ON (
        tgt.ENCODED_KEY = src.ENCODED_KEY
   )
WHEN MATCHED AND METADATA$ACTION IN ( 'INSERT', 'UPDATE' ) THEN
    UPDATE SET tgt.DUE_DATE = src.DUE_DATE,
		tgt.FEES_DUE = src.FEES_DUE,
        tgt.FEES_PAID = src.FEES_PAID,
        tgt.INTEREST_DUE = src.INTEREST_DUE,
        tgt.INTEREST_PAID = src.INTEREST_PAID,
        tgt.PENALTY_DUE = src.PENALTY_DUE,
        tgt.PENALTY_PAID = src.PENALTY_PAID,
        tgt.PRINCIPAL_DUE = src.PRINCIPAL_DUE,
        tgt.PRINCIPAL_PAID = src.PRINCIPAL_PAID,
        tgt.STATE = src.STATE,
        tgt.TAX_FEES_DUE = src.TAX_FEES_DUE,
        tgt.TAX_FEES_PAID = src.TAX_FEES_PAID,
        tgt.TAX_INTEREST_DUE = src.TAX_INTEREST_DUE,
        tgt.TAX_INTEREST_PAID = src.TAX_INTEREST_PAID,
        tgt.TAX_PENALTY_DUE = src.TAX_PENALTY_DUE,
        tgt.TAX_PENALTY_PAID = src.TAX_PENALTY_PAID    
WHEN NOT MATCHED AND METADATA$ACTION IN ( 'INSERT', 'UPDATE' ) THEN
    INSERT
    (	FACT_KEY,
        FACT_LOAN_ACCOUNTS_FK,
        DUE_DATE,
        ENCODED_KEY,
        FEES_DUE,
        FEES_PAID,
        INTEREST_DUE,
        INTEREST_PAID,
        PARENT_ACCOUNT_KEY,
        PENALTY_DUE,
        PENALTY_PAID,
        PRINCIPAL_DUE,
        PRINCIPAL_PAID,
        STATE,
        TAX_FEES_DUE,
        TAX_FEES_PAID,
        TAX_INTEREST_DUE,
        TAX_INTEREST_PAID,
        TAX_PENALTY_DUE,
        TAX_PENALTY_PAID
    )
    VALUES
    (MD5(src.ENCODED_KEY),	
	 LENDX_SANDBOX.LENDX_DW.GET_LOAN_ACCOUNT_KEY(src.PARENT_ACCOUNT_KEY),
     src.DUE_DATE,
     src.ENCODED_KEY,
     src.FEES_DUE,
     src.FEES_PAID,
     src.INTEREST_DUE,
     src.INTEREST_PAID,
     src.PARENT_ACCOUNT_KEY,
     src.PENALTY_DUE,
     src.PENALTY_PAID,
     src.PRINCIPAL_DUE,
     src.PRINCIPAL_PAID,
     src.STATE,
     src.TAX_FEES_DUE,
     src.TAX_FEES_PAID,
     src.TAX_INTEREST_DUE,
     src.TAX_INTEREST_PAID,
     src.TAX_PENALTY_DUE,
     src.TAX_PENALTY_PAID     
    );


CREATE OR REPLACE TASK LENDX_SANDBOX.LENDX_DW.STG_INSTALLMENTS
WAREHOUSE = COMPUTE_WH
AFTER LENDX_SANDBOX.LENDX_DW.FACT_LOAN_REPAYMENTS
WHEN
system$stream_has_data('LENDX_SANDBOX.LENDX_STG.RAW_INSTALLMENTS_STREAM')
AS
MERGE INTO LENDX_SANDBOX.LENDX_STG.STG_INSTALLMENTS AS tgt
USING LENDX_SANDBOX.LENDX_STG.RAW_INSTALLMENTS_STREAM AS src
ON (
        tgt.ENCODED_KEY = src.ENCODED_KEY
   )
WHEN MATCHED AND METADATA$ACTION IN ( 'INSERT', 'UPDATE' ) THEN
    UPDATE SET tgt.INSTALLMENT_INTEREST_AMOUNT_DUE = src.INTEREST:amount:due::number(10,2),
               tgt.INSTALLMENT_INTEREST_AMOUNT_EXPECTED = src.INTEREST:amount:expected::number(10,2),
               tgt.INSTALLMENT_INTEREST_AMOUNT_PAID = src.INTEREST:amount:paid::number(10,2),
               tgt.INSTALLMENT_INTEREST_TAX_DUE = src.INTEREST:tax:due::number(10,2),
               tgt.INSTALLMENT_INTEREST_TAX_EXPECTED = src.INTEREST:tax:expected::number(10,2),
               tgt.INSTALLMENT_INTEREST_TAX_PAID = src.INTEREST:tax:paid::number(10,2),
               tgt.INSTALLMENT_LAST_PAID_DATE = src.LAST_PAID_DATE,
               tgt.INSTALLMENT_NUMBER = src.NUMBER,
               tgt.INSTALLMENT_PENALTY_AMOUNT_DUE = src.PENALTY:amount:due::number(10,2),
               tgt.INSTALLMENT_PENALTY_AMOUNT_EXPECTED = src.PENALTY:amount:expected::number(10,2),
               tgt.INSTALLMENT_PENALTY_AMOUNT_PAID = src.PENALTY:amount:paid::number(10,2),
               tgt.INSTALLMENT_PENALTY_TAX_DUE = src.PENALTY:tax:due::number(10,2),
               tgt.INSTALLMENT_PENALTY_TAX_EXPECTED = src.PENALTY:tax:expected::number(10,2),
               tgt.INSTALLMENT_PENALTY_TAX_PAID = src.PENALTY:tax:paid::number(10,2),
               tgt.INSTALLMENT_REPAID_DATE = src.REPAID_DATE,
               tgt.INSTALLMENT_STATE = src.STATE
WHEN NOT MATCHED AND METADATA$ACTION IN ( 'INSERT', 'UPDATE' ) THEN
    INSERT
    (
        ENCODED_KEY,
        INSTALLMENT_INTEREST_AMOUNT_DUE,
        INSTALLMENT_INTEREST_AMOUNT_EXPECTED,
        INSTALLMENT_INTEREST_AMOUNT_PAID,
        INSTALLMENT_INTEREST_TAX_DUE,
        INSTALLMENT_INTEREST_TAX_EXPECTED,
        INSTALLMENT_INTEREST_TAX_PAID,
        INSTALLMENT_LAST_PAID_DATE,
        INSTALLMENT_NUMBER,
        INSTALLMENT_PENALTY_AMOUNT_DUE,
        INSTALLMENT_PENALTY_AMOUNT_EXPECTED,
        INSTALLMENT_PENALTY_AMOUNT_PAID,
        INSTALLMENT_PENALTY_TAX_DUE,
        INSTALLMENT_PENALTY_TAX_EXPECTED,
        INSTALLMENT_PENALTY_TAX_PAID,
        INSTALLMENT_REPAID_DATE,
        INSTALLMENT_STATE,
		PARENT_ACCOUNT_KEY
    )
    VALUES
    (src.ENCODED_KEY,
     src.INTEREST:amount:due::number(10,2),
     src.INTEREST:amount:expected::number(10,2),
     src.INTEREST:amount:paid::number(10,2),
     src.INTEREST:tax:due::number(10,2),
     src.INTEREST:tax:expected::number(10,2),
     src.INTEREST:tax:paid::number(10,2),
     src.LAST_PAID_DATE,
     src.NUMBER,
     src.PENALTY:amount:due::number(10,2),
     src.PENALTY:amount:expected::number(10,2),
     src.PENALTY:amount:paid::number(10,2),
     src.PENALTY:tax:due::number(10,2),
     src.PENALTY:tax:expected::number(10,2),
     src.PENALTY:tax:paid::number(10,2),
     src.REPAID_DATE,
     src.STATE,
	 src.PARENT_ACCOUNT_KEY
    );


CREATE OR REPLACE TASK LENDX_SANDBOX.LENDX_DW.STG_LOAN_REPAYMENTS_HISTORY
WAREHOUSE = COMPUTE_WH
AFTER LENDX_SANDBOX.LENDX_DW.FACT_LOAN_ACCOUNTS
WHEN
system$stream_has_data('LENDX_SANDBOX.LENDX_STG.RAW_LOAN_REPAYMENTS_HISTORY_STREAM')
AS
    INSERT INTO LENDX_STG.STG_LOAN_REPAYMENTS_HISTORY
    (	FACT_KEY,
        FACT_LOAN_ACCOUNTS_FK,
        DUE_DATE,
        ENCODED_KEY,
        FEES_DUE,
        FEES_PAID,
        INTEREST_DUE,
        INTEREST_PAID,
        PARENT_ACCOUNT_KEY,
        PENALTY_DUE,
        PENALTY_PAID,
        PRINCIPAL_DUE,
        PRINCIPAL_PAID,
        STATE,
        TAX_FEES_DUE,
        TAX_FEES_PAID,
        TAX_INTEREST_DUE,
        TAX_INTEREST_PAID,
        TAX_PENALTY_DUE,
        TAX_PENALTY_PAID,
		SEQUENCE_NUMBER
    )
    SELECT 
     MD5(src.ENCODED_KEY),	
	 LENDX_SANDBOX.LENDX_DW.GET_LOAN_ACCOUNT_KEY(src.PARENT_ACCOUNT_KEY),
     src.DUE_DATE,
     src.ENCODED_KEY,
     src.FEES_DUE,
     src.FEES_PAID,
     src.INTEREST_DUE,
     src.INTEREST_PAID,
     src.PARENT_ACCOUNT_KEY,
     src.PENALTY_DUE,
     src.PENALTY_PAID,
     src.PRINCIPAL_DUE,
     src.PRINCIPAL_PAID,
     src.STATE,
     src.TAX_FEES_DUE,
     src.TAX_FEES_PAID,
     src.TAX_INTEREST_DUE,
     src.TAX_INTEREST_PAID,
     src.TAX_PENALTY_DUE,
     src.TAX_PENALTY_PAID ,
     NULL
	FROM LENDX_SANDBOX.LENDX_STG.RAW_LOAN_REPAYMENTS_HISTORY_STREAM src
    WHERE METADATA$ACTION IN ('INSERT','UPDATE');


CREATE OR REPLACE TASK LENDX_SANDBOX.LENDX_DW.SET_REPAYMENTS_HISTORY_SEQ
WAREHOUSE = COMPUTE_WH
AFTER LENDX_SANDBOX.LENDX_DW.STG_LOAN_REPAYMENTS_HISTORY
AS
	UPDATE LENDX_STG.STG_LOAN_REPAYMENTS_HISTORY
	SET SEQUENCE_NUMBER = LENDX_SANDBOX.LENDX_DW.GET_REPAYMENT_NEXT_SEQUENCE_NUMBER(STG_LOAN_REPAYMENTS_HISTORY.PARENT_ACCOUNT_KEY)
	WHERE STG_LOAN_REPAYMENTS_HISTORY.SEQUENCE_NUMBER IS NULL;
	


ALTER TASK LENDX_SANDBOX.LENDX_DW.STG_ORIGINATOR RESUME;
ALTER TASK LENDX_SANDBOX.LENDX_DW.STG_BORROWER RESUME;
ALTER TASK LENDX_SANDBOX.LENDX_DW.STG_LOAN_PRODUCT RESUME;
ALTER TASK LENDX_SANDBOX.LENDX_DW.STG_LOAN_ACCOUNTS RESUME;
ALTER TASK LENDX_SANDBOX.LENDX_DW.STG_LOAN_REPAYMENTS RESUME;
ALTER TASK LENDX_SANDBOX.LENDX_DW.STG_INSTALLMENTS RESUME;
ALTER TASK LENDX_SANDBOX.LENDX_DW.STG_LOAN_REPAYMENTS_HISTORY RESUME;
ALTER TASK LENDX_SANDBOX.LENDX_DW.SET_REPAYMENTS_HISTORY_SEQ RESUME;



--- STG to DW -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

CREATE OR REPLACE TASK LENDX_SANDBOX.LENDX_DW.DIM_ORIGINATOR
WAREHOUSE = COMPUTE_WH
AFTER LENDX_SANDBOX.LENDX_DW.STG_ORIGINATOR
AS
MERGE INTO LENDX_SANDBOX.LENDX_DW.DIM_ORIGINATOR AS tgt
USING LENDX_SANDBOX.LENDX_STG.STG_ORIGINATOR AS src
ON (tgt.DIMENSION_KEY = src.DIMENSION_KEY)
WHEN MATCHED THEN
    UPDATE SET tgt.CREATION_DATE = src.CREATION_DATE,
               tgt.EMAIL_ADDRESS = src.EMAIL_ADDRESS,
               tgt.ID = src.ID,
               tgt.LAST_MODIFIED_DATE = src.LAST_MODIFIED_DATE,
               tgt."NAME" = src."NAME",
               tgt.NOTES = src.NOTES,
               tgt.PHONE_NUMBER = src.PHONE_NUMBER,
               tgt.STATE = src.STATE,
               tgt.AUDIT_LAST_MODIFIED_DATE = CURRENT_TIMESTAMP
WHEN NOT MATCHED THEN
    INSERT
    (
        DIMENSION_KEY,
        CREATION_DATE,
        EMAIL_ADDRESS,
        ENCODED_KEY,
        ID,
        LAST_MODIFIED_DATE,
        "NAME",
        NOTES,
        PHONE_NUMBER,
        STATE,
        AUDIT_LOADED_DATE
    )
    VALUES
    (src.DIMENSION_KEY,
     src.CREATION_DATE,
     src.EMAIL_ADDRESS,
     src.ENCODED_KEY,
     src.ID,
     src.LAST_MODIFIED_DATE,
     src."NAME",
     src.NOTES,
     src.PHONE_NUMBER,
     src.STATE,
     CURRENT_TIMESTAMP
    );


CREATE OR REPLACE TASK LENDX_SANDBOX.LENDX_DW.DIM_BORROWER
WAREHOUSE = COMPUTE_WH
AFTER LENDX_SANDBOX.LENDX_DW.STG_BORROWER
AS
MERGE INTO LENDX_SANDBOX.LENDX_DW.DIM_BORROWER AS tgt
USING LENDX_SANDBOX.LENDX_STG.STG_BORROWER AS src
ON (tgt.DIMENSION_KEY = src.DIMENSION_KEY)
WHEN MATCHED THEN
    UPDATE SET tgt.ACTIVATION_DATE = src.ACTIVATION_DATE,
               tgt.CITY = src.CITY,
               tgt.COUNTRY = src.COUNTRY,
               tgt.STREET_ADDRESS_LINE1 = src.STREET_ADDRESS_LINE1,
               tgt.STREET_ADDRESS_LINE2 = src.STREET_ADDRESS_LINE2,
               tgt.POST_CODE = src.POST_CODE,
               tgt.REGION = src.REGION,
               tgt.BIRTH_DATE = src.BIRTH_DATE,
               tgt.APPROVED_DATE = src.APPROVED_DATE,
               tgt.CLIENT_ROLE_KEY = src.CLIENT_ROLE_KEY,
               tgt.CREATION_DATE = src.CREATION_DATE,
               tgt.EMAIL_ADDRESS = src.EMAIL_ADDRESS,
               tgt.FIRST_NAME = src.FIRST_NAME,
               tgt.GENDER = src.GENDER,
               tgt.GROUP_LOAN_CYCLE = src.GROUP_LOAN_CYCLE,
               tgt.ID = src.ID,
               tgt.LAST_MODIFIED_DATE = src.LAST_MODIFIED_DATE,
               tgt.LAST_NAME = src.LAST_NAME,
               tgt.NOTES = src.NOTES,
               tgt.MIDDLE_NAME = src.MIDDLE_NAME,
               tgt.HOME_PHONE = src.HOME_PHONE,
               tgt.MOBILE_PHONE = src.MOBILE_PHONE,
               tgt.PREFERRED_LANGUAGE = src.PREFERRED_LANGUAGE,
               tgt.STATE = src.STATE,
			   tgt.ASSIGNED_ORIGINATOR_KEY = src.ASSIGNED_ORIGINATOR_KEY,
               tgt.AUDIT_LAST_MODIFIED_DATE = CURRENT_TIMESTAMP
WHEN NOT MATCHED THEN
    INSERT
    (
        DIMENSION_KEY,
        ACTIVATION_DATE,
        CITY,
        COUNTRY,
        STREET_ADDRESS_LINE1,
        STREET_ADDRESS_LINE2,
        POST_CODE,
        REGION,
        BIRTH_DATE,
        APPROVED_DATE,
        CLIENT_ROLE_KEY,
        CREATION_DATE,
        EMAIL_ADDRESS,
        ENCODED_KEY,
        FIRST_NAME,
        GENDER,
        GROUP_LOAN_CYCLE,
        ID,
        LAST_MODIFIED_DATE,
        LAST_NAME,
        NOTES,
        MIDDLE_NAME,
        HOME_PHONE,
        MOBILE_PHONE,
        PREFERRED_LANGUAGE,
        STATE,
		ASSIGNED_ORIGINATOR_KEY,
        AUDIT_LOADED_DATE
    )
    VALUES
    (src.DIMENSION_KEY,
     src.ACTIVATION_DATE,
     src.CITY,
     src.COUNTRY,
     src.STREET_ADDRESS_LINE1,
     src.STREET_ADDRESS_LINE2,
     src.POST_CODE,
     src.REGION,
     src.BIRTH_DATE,
     src.APPROVED_DATE,
     src.CLIENT_ROLE_KEY,
     src.CREATION_DATE,
     src.EMAIL_ADDRESS,
     src.ENCODED_KEY,
     src.FIRST_NAME,
     src.GENDER,
     src.GROUP_LOAN_CYCLE,
     src.ID,
     src.LAST_MODIFIED_DATE,
     src.LAST_NAME,
     src.NOTES,
     src.MIDDLE_NAME,
     src.HOME_PHONE,
     src.MOBILE_PHONE,
     src.PREFERRED_LANGUAGE,
     src.STATE,
	 src.ASSIGNED_ORIGINATOR_KEY,
     CURRENT_TIMESTAMP
    );


CREATE OR REPLACE TASK LENDX_SANDBOX.LENDX_DW.DIM_LOAN_PRODUCT
WAREHOUSE = COMPUTE_WH
AFTER LENDX_SANDBOX.LENDX_DW.STG_LOAN_PRODUCT
AS
MERGE INTO LENDX_SANDBOX.LENDX_DW.DIM_LOAN_PRODUCT AS tgt
USING LENDX_SANDBOX.LENDX_STG.STG_LOAN_PRODUCT AS src
ON (tgt.DIMENSION_KEY = src.DIMENSION_KEY)
WHEN MATCHED THEN
    UPDATE SET tgt.ACCOUNTING_METHOD = src.ACCOUNTING_METHOD,
               tgt.ACCOUNT_INITIAL_STATE = src.ACCOUNT_INITIAL_STATE,
               tgt.ACCOUNT_LINKING_ENABLED = src.ACCOUNT_LINKING_ENABLED,
               tgt.ACTIVATED = src.ACTIVATED,
               tgt.ALLOW_ARBITRARY_FEES = src.ALLOW_ARBITRARY_FEES,
               tgt.AMORTIZATION_METHOD = src.AMORTIZATION_METHOD,
               tgt.AUTO_CREATE_LINKED_ACCOUNTS = src.AUTO_CREATE_LINKED_ACCOUNTS,
               tgt.AUTO_LINK_ACCOUNTS = src.AUTO_LINK_ACCOUNTS,
               tgt.DAYS_IN_YEAR = src.DAYS_IN_YEAR,
               tgt.DEFAULT_LOAN_AMOUNT = src.DEFAULT_LOAN_AMOUNT,
               tgt.DEFAULT_PRINCIPAL_REPAYMENT_INTERVAL = src.DEFAULT_PRINCIPAL_REPAYMENT_INTERVAL,
               tgt.DEFAULT_REPAYMENT_PERIOD_COUNT = src.DEFAULT_REPAYMENT_PERIOD_COUNT,
               tgt.FOR_HYBRID_GROUPS = src.FOR_HYBRID_GROUPS,
               tgt.FOR_INDIVIDUALS = src.FOR_INDIVIDUALS,
               tgt.FOR_PURE_GROUPS = src.FOR_PURE_GROUPS,
               tgt.FUTURE_PAYMENTS_ACCEPTANCE = src.FUTURE_PAYMENTS_ACCEPTANCE,
               tgt.GRACE_PERIOD_TYPE = src.GRACE_PERIOD_TYPE,
               tgt.ID = src.ID,
               tgt.ID_GENERATOR_TYPE = src.ID_GENERATOR_TYPE,
               tgt.ID_PATTERN = src.ID_PATTERN,
               tgt.INTEREST_ACCRUED_ACCOUNTING_METHOD = src.INTEREST_ACCRUED_ACCOUNTING_METHOD,
               tgt.INTEREST_APPLICATION_METHOD = src.INTEREST_APPLICATION_METHOD,
               tgt.INTEREST_BALANCE_CALCULATION_METHOD = src.INTEREST_BALANCE_CALCULATION_METHOD,
               tgt.INTEREST_CALCULATION_METHOD = src.INTEREST_CALCULATION_METHOD,
               tgt.LAST_MODIFIED_DATE = src.LAST_MODIFIED_DATE,
               tgt.LATE_PAYMENTS_RECALCULATION_METHOD = src.LATE_PAYMENTS_RECALCULATION_METHOD,
               tgt.LINE_OF_CREDIT_REQUIREMENT = src.LINE_OF_CREDIT_REQUIREMENT,
               tgt.LOAN_FEES = src.LOAN_FEES,
               tgt.LOAN_PENALTY_CALCULATION_METHOD = src.LOAN_PENALTY_CALCULATION_METHOD,
               tgt.LOAN_PRODUCT_RULES = src.LOAN_PRODUCT_RULES,
               tgt.LOAN_PRODUCT_TYPE = src.LOAN_PRODUCT_TYPE,
               tgt.MAX_NUMBER_OF_DISBURSEMENT_TRANCHES = src.MAX_NUMBER_OF_DISBURSEMENT_TRANCHES,
               tgt.PAYMENT_METHOD = src.PAYMENT_METHOD,
               tgt.PREPAYMENT_ACCEPTANCE = src.PREPAYMENT_ACCEPTANCE,
               tgt.PRODUCT_DESCRIPTION = src.PRODUCT_DESCRIPTION,
               tgt.PRODUCT_NAME = src.PRODUCT_NAME,
               tgt.REPAYMENT_ALLOCATION_ORDER = src.REPAYMENT_ALLOCATION_ORDER,
               tgt.REPAYMENT_CURRENCY_ROUNDING = src.REPAYMENT_CURRENCY_ROUNDING,
               tgt.REPAYMENT_ELEMENTS_ROUNDING_METHOD = src.REPAYMENT_ELEMENTS_ROUNDING_METHOD,
               tgt.REPAYMENT_PERIOD_UNIT = src.REPAYMENT_PERIOD_UNIT,
               tgt.REPAYMENT_RESCHEDULING_METHOD = src.REPAYMENT_RESCHEDULING_METHOD,
               tgt.REPAYMENT_SCHEDULE_EDIT_OPTIONS = src.REPAYMENT_SCHEDULE_EDIT_OPTIONS,
               tgt.REPAYMENT_SCHEDULE_METHOD = src.REPAYMENT_SCHEDULE_METHOD,
               tgt.ROUNDING_REPAYMENT_SCHEDULE_METHOD = src.ROUNDING_REPAYMENT_SCHEDULE_METHOD,
               tgt.SCHEDULE_DUE_DATES_METHOD = src.SCHEDULE_DUE_DATES_METHOD,
               tgt.SCHEDULE_INTEREST_DAYS_COUNT_METHOD = src.SCHEDULE_INTEREST_DAYS_COUNT_METHOD,
               tgt.SETTLEMENT_OPTIONS = src.SETTLEMENT_OPTIONS,
               tgt.TAXES_ON_FEES_ENABLED = src.TAXES_ON_FEES_ENABLED,
               tgt.TAXES_ON_INTEREST_ENABLED = src.TAXES_ON_INTEREST_ENABLED,
               tgt.TAXES_ON_PENALTY_ENABLED = src.TAXES_ON_PENALTY_ENABLED,
               tgt.APPLY_INTEREST_ON_PREPAYMENT_METHOD = src.APPLY_INTEREST_ON_PREPAYMENT_METHOD,
               tgt.INTEREST_RATE_ENCODED_KEY = src.INTEREST_RATE_ENCODED_KEY,
			   tgt.DEFAULT_INTEREST_RATE = src.DEFAULT_INTEREST_RATE,
               tgt.INTEREST_CHARGE_FREQUENCY = src.INTEREST_CHARGE_FREQUENCY,
               tgt.INTEREST_CHARGE_FREQUENCY_COUNT = src.INTEREST_CHARGE_FREQUENCY_COUNT,
               tgt.INTEREST_RATE_SOURCE = src.INTEREST_RATE_SOURCE,
               tgt.INTEREST_RATE_TERMS = src.INTEREST_RATE_TERMS,
               tgt.PRODUCT_SECURITY_ENCODED_KEY = src.PRODUCT_SECURITY_ENCODED_KEY,
               tgt.PRODUCT_SECURITY_IS_COLLATERAL_ENABLED = src.PRODUCT_SECURITY_IS_COLLATERAL_ENABLED,
               tgt.PRODUCT_SECURITY_IS_GUARANTORS_ENABLED = src.PRODUCT_SECURITY_IS_GUARANTORS_ENABLED,
               tgt.PRODUCT_SECURITY_IS_INVESTOR_FUNDS_ENABLED = src.PRODUCT_SECURITY_IS_INVESTOR_FUNDS_ENABLED,
               tgt.PRODUCT_SECURITY_REQUIRED_GUARANTIES = src.PRODUCT_SECURITY_REQUIRED_GUARANTIES,
               tgt.AUDIT_LAST_MODIFIED_DATE = CURRENT_TIMESTAMP
WHEN NOT MATCHED THEN
    INSERT
    (
        DIMENSION_KEY,
        ACCOUNTING_METHOD,
        ACCOUNT_INITIAL_STATE,
        ACCOUNT_LINKING_ENABLED,
        ACTIVATED,
        ALLOW_ARBITRARY_FEES,
        AMORTIZATION_METHOD,
        AUTO_CREATE_LINKED_ACCOUNTS,
        AUTO_LINK_ACCOUNTS,
        CREATION_DATE,
        DAYS_IN_YEAR,
        DEFAULT_LOAN_AMOUNT,
        DEFAULT_PRINCIPAL_REPAYMENT_INTERVAL,
        DEFAULT_REPAYMENT_PERIOD_COUNT,
        ENCODED_KEY,
        FOR_HYBRID_GROUPS,
        FOR_INDIVIDUALS,
        FOR_PURE_GROUPS,
        FUTURE_PAYMENTS_ACCEPTANCE,
        GRACE_PERIOD_TYPE,
        ID,
        ID_GENERATOR_TYPE,
        ID_PATTERN,
        INTEREST_ACCRUED_ACCOUNTING_METHOD,
        INTEREST_APPLICATION_METHOD,
        INTEREST_BALANCE_CALCULATION_METHOD,
        INTEREST_CALCULATION_METHOD,
        LAST_MODIFIED_DATE,
        LATE_PAYMENTS_RECALCULATION_METHOD,
        LINE_OF_CREDIT_REQUIREMENT,
        LOAN_FEES,
        LOAN_PENALTY_CALCULATION_METHOD,
        LOAN_PRODUCT_RULES,
        LOAN_PRODUCT_TYPE,
        MAX_NUMBER_OF_DISBURSEMENT_TRANCHES,
        PAYMENT_METHOD,
        PREPAYMENT_ACCEPTANCE,
        PRODUCT_DESCRIPTION,
        PRODUCT_NAME,
        REPAYMENT_ALLOCATION_ORDER,
        REPAYMENT_CURRENCY_ROUNDING,
        REPAYMENT_ELEMENTS_ROUNDING_METHOD,
        REPAYMENT_PERIOD_UNIT,
        REPAYMENT_RESCHEDULING_METHOD,
        REPAYMENT_SCHEDULE_EDIT_OPTIONS,
        REPAYMENT_SCHEDULE_METHOD,
        ROUNDING_REPAYMENT_SCHEDULE_METHOD,
        SCHEDULE_DUE_DATES_METHOD,
        SCHEDULE_INTEREST_DAYS_COUNT_METHOD,
        SETTLEMENT_OPTIONS,
        TAXES_ON_FEES_ENABLED,
        TAXES_ON_INTEREST_ENABLED,
        TAXES_ON_PENALTY_ENABLED,
        APPLY_INTEREST_ON_PREPAYMENT_METHOD,
        INTEREST_RATE_ENCODED_KEY,
		DEFAULT_INTEREST_RATE,
        INTEREST_CHARGE_FREQUENCY,
        INTEREST_CHARGE_FREQUENCY_COUNT,
        INTEREST_RATE_SOURCE,
        INTEREST_RATE_TERMS,
        PRODUCT_SECURITY_ENCODED_KEY,
        PRODUCT_SECURITY_IS_COLLATERAL_ENABLED,
        PRODUCT_SECURITY_IS_GUARANTORS_ENABLED,
        PRODUCT_SECURITY_IS_INVESTOR_FUNDS_ENABLED,
        PRODUCT_SECURITY_REQUIRED_GUARANTIES,
        AUDIT_LOADED_DATE
    )
    VALUES
    (src.DIMENSION_KEY,
     src.ACCOUNTING_METHOD,
     src.ACCOUNT_INITIAL_STATE,
     src.ACCOUNT_LINKING_ENABLED,
     src.ACTIVATED,
     src.ALLOW_ARBITRARY_FEES,
     src.AMORTIZATION_METHOD,
     src.AUTO_CREATE_LINKED_ACCOUNTS,
     src.AUTO_LINK_ACCOUNTS,
     src.CREATION_DATE,
     src.DAYS_IN_YEAR,
     src.DEFAULT_LOAN_AMOUNT,
     src.DEFAULT_PRINCIPAL_REPAYMENT_INTERVAL,
     src.DEFAULT_REPAYMENT_PERIOD_COUNT,
     src.ENCODED_KEY,
     src.FOR_HYBRID_GROUPS,
     src.FOR_INDIVIDUALS,
     src.FOR_PURE_GROUPS,
     src.FUTURE_PAYMENTS_ACCEPTANCE,
     src.GRACE_PERIOD_TYPE,
     src.ID,
     src.ID_GENERATOR_TYPE,
     src.ID_PATTERN,
     src.INTEREST_ACCRUED_ACCOUNTING_METHOD,
     src.INTEREST_APPLICATION_METHOD,
     src.INTEREST_BALANCE_CALCULATION_METHOD,
     src.INTEREST_CALCULATION_METHOD,
     src.LAST_MODIFIED_DATE,
     src.LATE_PAYMENTS_RECALCULATION_METHOD,
     src.LINE_OF_CREDIT_REQUIREMENT,
     src.LOAN_FEES,
     src.LOAN_PENALTY_CALCULATION_METHOD,
     src.LOAN_PRODUCT_RULES,
     src.LOAN_PRODUCT_TYPE,
     src.MAX_NUMBER_OF_DISBURSEMENT_TRANCHES,
     src.PAYMENT_METHOD,
     src.PREPAYMENT_ACCEPTANCE,
     src.PRODUCT_DESCRIPTION,
     src.PRODUCT_NAME,
     src.REPAYMENT_ALLOCATION_ORDER,
     src.REPAYMENT_CURRENCY_ROUNDING,
     src.REPAYMENT_ELEMENTS_ROUNDING_METHOD,
     src.REPAYMENT_PERIOD_UNIT,
     src.REPAYMENT_RESCHEDULING_METHOD,
     src.REPAYMENT_SCHEDULE_EDIT_OPTIONS,
     src.REPAYMENT_SCHEDULE_METHOD,
     src.ROUNDING_REPAYMENT_SCHEDULE_METHOD,
     src.SCHEDULE_DUE_DATES_METHOD,
     src.SCHEDULE_INTEREST_DAYS_COUNT_METHOD,
     src.SETTLEMENT_OPTIONS,
     src.TAXES_ON_FEES_ENABLED,
     src.TAXES_ON_INTEREST_ENABLED,
     src.TAXES_ON_PENALTY_ENABLED,
     src.APPLY_INTEREST_ON_PREPAYMENT_METHOD,
     src.INTEREST_RATE_ENCODED_KEY,
	 src.DEFAULT_INTEREST_RATE,
     src.INTEREST_CHARGE_FREQUENCY,
     src.INTEREST_CHARGE_FREQUENCY_COUNT,
     src.INTEREST_RATE_SOURCE,
     src.INTEREST_RATE_TERMS,
     src.PRODUCT_SECURITY_ENCODED_KEY,
     src.PRODUCT_SECURITY_IS_COLLATERAL_ENABLED,
     src.PRODUCT_SECURITY_IS_GUARANTORS_ENABLED,
     src.PRODUCT_SECURITY_IS_INVESTOR_FUNDS_ENABLED,
     src.PRODUCT_SECURITY_REQUIRED_GUARANTIES,
     CURRENT_TIMESTAMP
    );


CREATE OR REPLACE TASK LENDX_SANDBOX.LENDX_DW.FACT_LOAN_ACCOUNTS
WAREHOUSE = COMPUTE_WH
AFTER LENDX_SANDBOX.LENDX_DW.STG_LOAN_ACCOUNTS
AS
MERGE INTO LENDX_SANDBOX.LENDX_DW.FACT_LOAN_ACCOUNTS AS tgt
USING LENDX_SANDBOX.LENDX_STG.STG_LOAN_ACCOUNTS AS src
ON (tgt.FACT_KEY = src.FACT_KEY)
WHEN MATCHED THEN
    UPDATE SET tgt.DIM_TIME_APPROVED = src.DIM_TIME_APPROVED,
			   tgt.ACCOUNT_ARREARS_DATE_CALCULATION_METHOD = src.ACCOUNT_ARREARS_DATE_CALCULATION_METHOD,
               tgt.ACCOUNT_ARREARS_ENCODED_KEY = src.ACCOUNT_ARREARS_ENCODED_KEY,
               tgt.ACCOUNT_ARREARS_NON_WORKING_DAYS_METHOD = src.ACCOUNT_ARREARS_NON_WORKING_DAYS_METHOD,
               tgt.ACCOUNT_ARREARS_TOLERANCE_CALCULATION_METHOD = src.ACCOUNT_ARREARS_TOLERANCE_CALCULATION_METHOD,
               tgt.ACCOUNT_ARREARS_TOLERANCE_PERIOD = src.ACCOUNT_ARREARS_TOLERANCE_PERIOD,
               tgt.ACCOUNT_HOLDER_TYPE = src.ACCOUNT_HOLDER_TYPE,
               tgt.ACCOUNT_STATE = src.ACCOUNT_STATE,
               tgt.ACCOUNT_SUB_STATE = src.ACCOUNT_SUB_STATE,
               tgt.ACCRUED_INTEREST = src.ACCRUED_INTEREST,
               tgt.ACCRUED_PENALTY = src.ACCRUED_PENALTY,
               tgt.ACTIVATION_TRANSACTION_KEY = src.ACTIVATION_TRANSACTION_KEY,
               tgt.ALLOW_OFFSET = src.ALLOW_OFFSET,
               tgt.APPROVED_DATE = src.APPROVED_DATE,
               tgt.ARREARS_TOLERANCE_PERIOD = src.ARREARS_TOLERANCE_PERIOD,
               tgt.ASSETS = src.ASSETS,             
			   tgt.FEES_BALANCE = src.FEES_BALANCE,
               tgt.FEES_DUE = src.FEES_DUE,
               tgt.FEES_PAID = src.FEES_PAID,
               tgt.INTEREST_BALANCE = src.INTEREST_BALANCE,
               tgt.INTEREST_DUE = src.INTEREST_DUE,
               tgt.INTEREST_FROM_ARREARS_BALANCE = src.INTEREST_FROM_ARREARS_BALANCE,
               tgt.INTEREST_FROM_ARREARS_DUE = src.INTEREST_FROM_ARREARS_DUE,
               tgt.INTEREST_FROM_ARREARS_PAID = src.INTEREST_FROM_ARREARS_PAID,
               tgt.INTEREST_PAID = src.INTEREST_PAID,
               tgt.PENALTY_BALANCE = src.PENALTY_BALANCE,
               tgt.PENALTY_DUE = src.PENALTY_DUE,
               tgt.PENALTY_PAID = src.PENALTY_PAID,
               tgt.PRINCIPAL_BALANCE = src.PRINCIPAL_BALANCE,
               tgt.PRINCIPAL_DUE = src.PRINCIPAL_DUE,
               tgt.PRINCIPAL_PAID = src.PRINCIPAL_PAID,
               tgt.REDRAW_BALANCE = src.REDRAW_BALANCE,
               tgt.CLOSED_DATE = src.CLOSED_DATE,
               tgt.CUSTOM_FIELDS = src.CUSTOM_FIELDS,
               tgt.DISBURSEMENT_DATE = src.DISBURSEMENT_DATE,
               tgt.EXPECTED_DISBURSEMENT_DATE = src.EXPECTED_DISBURSEMENT_DATE,
               tgt.FIRST_REPAYMENT_DATE = src.FIRST_REPAYMENT_DATE,
               tgt.FUNDING_SOURCES = src.FUNDING_SOURCES,
               tgt.FUTURE_PAYMENTS_ACCEPTANCE = src.FUTURE_PAYMENTS_ACCEPTANCE,
               tgt.GUARANTORS = src.GUARANTORS,
               tgt.ID = src.ID,
               tgt.INTEREST_FROM_ARREARS_ACCRUED = src.INTEREST_FROM_ARREARS_ACCRUED,
               tgt.ACCRUE_INTEREST_AFTER_MATURITY = src.ACCRUE_INTEREST_AFTER_MATURITY,
               tgt.INTEREST_APPLICATION_METHOD = src.INTEREST_APPLICATION_METHOD,
               tgt.INTEREST_BALANCE_CALCULATION_METHOD = src.INTEREST_BALANCE_CALCULATION_METHOD,
               tgt.INTEREST_CALCULATION_METHOD = src.INTEREST_CALCULATION_METHOD,
               tgt.INTEREST_CHARGE_FREQUENCY = src.INTEREST_CHARGE_FREQUENCY,
               tgt.INTEREST_RATE = src.INTEREST_RATE,
               tgt.INTEREST_RATE_SOURCE = src.INTEREST_RATE_SOURCE,
               tgt.INTEREST_TYPE = src.INTEREST_TYPE,
               tgt.LAST_ACCOUNT_APPRAISAL_DATE = src.LAST_ACCOUNT_APPRAISAL_DATE,
               tgt.LAST_INTEREST_APPLIED_DATE = src.LAST_INTEREST_APPLIED_DATE,
               tgt.LAST_MODIFIED_DATE = src.LAST_MODIFIED_DATE,
               tgt.LAST_SET_TO_ARREARS_DATE = src.LAST_SET_TO_ARREARS_DATE,
               tgt.LATE_PAYMENTS_RECALCULATION_METHOD = src.LATE_PAYMENTS_RECALCULATION_METHOD,
               tgt.LOAN_AMOUNT = src.LOAN_AMOUNT,
               tgt.LOAN_NAME = src.LOAN_NAME,
               tgt.ORIGINAL_ACCOUNT_KEY = src.ORIGINAL_ACCOUNT_KEY,
               tgt.PAYMENT_METHOD = src.PAYMENT_METHOD,
               tgt.LOAN_PENALTY_CALCULATION_METHOD = src.LOAN_PENALTY_CALCULATION_METHOD,
               tgt.PENALTY_RATE = src.PENALTY_RATE,
               tgt.APPLY_INTEREST_ON_PREPAYMENT_METHOD = src.APPLY_INTEREST_ON_PREPAYMENT_METHOD,
               tgt.PREPAYMENT_RECALCULATION_METHOD = src.PREPAYMENT_RECALCULATION_METHOD,
               tgt.RESCHEDULED_ACCOUNT_KEY = src.RESCHEDULED_ACCOUNT_KEY,
               tgt.GRACE_PERIOD = src.GRACE_PERIOD,
               tgt.GRACE_PERIOD_TYPE = src.GRACE_PERIOD_TYPE,
               tgt.HAS_CUSTOM_SCHEDULE = src.HAS_CUSTOM_SCHEDULE,
               tgt.PAYMENT_PLAN = src.PAYMENT_PLAN,
               tgt.PERIODIC_PAYMENT = src.PERIODIC_PAYMENT,
               tgt.PRINCIPAL_REPAYMENT_INTERVAL = src.PRINCIPAL_REPAYMENT_INTERVAL,
               tgt.REPAYMENT_INSTALLMENTS = src.REPAYMENT_INSTALLMENTS,
               tgt.REPAYMENT_PERIOD_COUNT = src.REPAYMENT_PERIOD_COUNT,
               tgt.REPAYMENT_PERIOD_UNIT = src.REPAYMENT_PERIOD_UNIT,
               tgt.REPAYMENT_SCHEDULE_METHOD = src.REPAYMENT_SCHEDULE_METHOD,
               tgt.SCHEDULE_DUE_DATES_METHOD = src.SCHEDULE_DUE_DATES_METHOD,
               tgt.TRANCHES = src.TRANCHES,
               tgt.LAST_INTEREST_REVIEW_DATE = src.LAST_INTEREST_REVIEW_DATE,
               tgt.CURRENCY_CODE = src.CURRENCY_CODE,
			   tgt.AUDIT_LAST_MODIFIED_DATE = CURRENT_TIMESTAMP
WHEN NOT MATCHED THEN
    INSERT
    (	FACT_KEY,
        DIM_ORIGINATOR,
        DIM_LOAN_PRODUCT,
        DIM_BORROWER,
        ENCODED_KEY,
		DIM_TIME_APPROVED,
        ACCOUNT_ARREARS_DATE_CALCULATION_METHOD,
        ACCOUNT_ARREARS_ENCODED_KEY,
        ACCOUNT_ARREARS_NON_WORKING_DAYS_METHOD,
        ACCOUNT_ARREARS_TOLERANCE_CALCULATION_METHOD,
        ACCOUNT_ARREARS_TOLERANCE_PERIOD,
        ACCOUNT_HOLDER_KEY,
        ACCOUNT_HOLDER_TYPE,
        ACCOUNT_STATE,
        ACCOUNT_SUB_STATE,
        ACCRUED_INTEREST,
        ACCRUED_PENALTY,
        ACTIVATION_TRANSACTION_KEY,
        ALLOW_OFFSET,
        APPROVED_DATE,
        ARREARS_TOLERANCE_PERIOD,
        ASSETS,
        ASSIGNED_BRANCH_KEY,
        FEES_BALANCE,
        FEES_DUE,
        FEES_PAID,
        INTEREST_BALANCE,
        INTEREST_DUE,
        INTEREST_FROM_ARREARS_BALANCE,
        INTEREST_FROM_ARREARS_DUE,
        INTEREST_FROM_ARREARS_PAID,
        INTEREST_PAID,
        PENALTY_BALANCE,
        PENALTY_DUE,
        PENALTY_PAID,
        PRINCIPAL_BALANCE,
        PRINCIPAL_DUE,
        PRINCIPAL_PAID,
        REDRAW_BALANCE,
        CLOSED_DATE,
        CREATION_DATE,
        CUSTOM_FIELDS,
        DISBURSEMENT_DATE,
        EXPECTED_DISBURSEMENT_DATE,
        FIRST_REPAYMENT_DATE,
        FUNDING_SOURCES,
        FUTURE_PAYMENTS_ACCEPTANCE,
        GUARANTORS,
        ID,
        INTEREST_FROM_ARREARS_ACCRUED,
        ACCRUE_INTEREST_AFTER_MATURITY,
        INTEREST_APPLICATION_METHOD,
        INTEREST_BALANCE_CALCULATION_METHOD,
        INTEREST_CALCULATION_METHOD,
        INTEREST_CHARGE_FREQUENCY,
        INTEREST_RATE,
        INTEREST_RATE_SOURCE,
        INTEREST_TYPE,
        LAST_ACCOUNT_APPRAISAL_DATE,
        LAST_INTEREST_APPLIED_DATE,
        LAST_MODIFIED_DATE,
        LAST_SET_TO_ARREARS_DATE,
        LATE_PAYMENTS_RECALCULATION_METHOD,
        LOAN_AMOUNT,
        LOAN_NAME,
        ORIGINAL_ACCOUNT_KEY,
        PAYMENT_METHOD,
        LOAN_PENALTY_CALCULATION_METHOD,
        PENALTY_RATE,
        APPLY_INTEREST_ON_PREPAYMENT_METHOD,
        PREPAYMENT_RECALCULATION_METHOD,
        PRODUCT_TYPE_KEY,
        RESCHEDULED_ACCOUNT_KEY,
        GRACE_PERIOD,
        GRACE_PERIOD_TYPE,
        HAS_CUSTOM_SCHEDULE,
        PAYMENT_PLAN,
        PERIODIC_PAYMENT,
        PRINCIPAL_REPAYMENT_INTERVAL,
        REPAYMENT_INSTALLMENTS,
        REPAYMENT_PERIOD_COUNT,
        REPAYMENT_PERIOD_UNIT,
        REPAYMENT_SCHEDULE_METHOD,
        SCHEDULE_DUE_DATES_METHOD,
        TRANCHES,
        LAST_INTEREST_REVIEW_DATE,
        CURRENCY_CODE,
		AUDIT_LOADED_DATE
    )
    VALUES
    (MD5(src.ENCODED_KEY),	
	 LENDX_SANDBOX.LENDX_DW.GET_ORIGINATOR_KEY(ASSIGNED_BRANCH_KEY),
     LENDX_SANDBOX.LENDX_DW.GET_LOAN_PRODUCT_KEY(PRODUCT_TYPE_KEY),
     LENDX_SANDBOX.LENDX_DW.GET_BORROWER_KEY(ACCOUNT_HOLDER_KEY),
     src.ENCODED_KEY,
	 src.DIM_TIME_APPROVED,
     src.ACCOUNT_ARREARS_DATE_CALCULATION_METHOD,
     src.ACCOUNT_ARREARS_ENCODED_KEY,
     src.ACCOUNT_ARREARS_NON_WORKING_DAYS_METHOD,
     src.ACCOUNT_ARREARS_TOLERANCE_CALCULATION_METHOD,
     src.ACCOUNT_ARREARS_TOLERANCE_PERIOD,
     src.ACCOUNT_HOLDER_KEY,
     src.ACCOUNT_HOLDER_TYPE,
     src.ACCOUNT_STATE,
     src.ACCOUNT_SUB_STATE,
     src.ACCRUED_INTEREST,
     src.ACCRUED_PENALTY,
     src.ACTIVATION_TRANSACTION_KEY,
     src.ALLOW_OFFSET,
     src.APPROVED_DATE,
     src.ARREARS_TOLERANCE_PERIOD,
     src.ASSETS,
     src.ASSIGNED_BRANCH_KEY,
     src.FEES_BALANCE,
     src.FEES_DUE,
     src.FEES_PAID,
     src.INTEREST_BALANCE,
     src.INTEREST_DUE,
     src.INTEREST_FROM_ARREARS_BALANCE,
     src.INTEREST_FROM_ARREARS_DUE,
     src.INTEREST_FROM_ARREARS_PAID,
     src.INTEREST_PAID,
     src.PENALTY_BALANCE,
     src.PENALTY_DUE,
     src.PENALTY_PAID,
     src.PRINCIPAL_BALANCE,
     src.PRINCIPAL_DUE,
     src.PRINCIPAL_PAID,
     src.REDRAW_BALANCE,
     src.CLOSED_DATE,
     src.CREATION_DATE,
     src.CUSTOM_FIELDS,
     src.DISBURSEMENT_DATE,
     src.EXPECTED_DISBURSEMENT_DATE,
     src.FIRST_REPAYMENT_DATE,
     src.FUNDING_SOURCES,
     src.FUTURE_PAYMENTS_ACCEPTANCE,
     src.GUARANTORS,
     src.ID,
     src.INTEREST_FROM_ARREARS_ACCRUED,
     src.ACCRUE_INTEREST_AFTER_MATURITY,
     src.INTEREST_APPLICATION_METHOD,
     src.INTEREST_BALANCE_CALCULATION_METHOD,
     src.INTEREST_CALCULATION_METHOD,
     src.INTEREST_CHARGE_FREQUENCY,
     src.INTEREST_RATE,
     src.INTEREST_RATE_SOURCE,
     src.INTEREST_TYPE,
     src.LAST_ACCOUNT_APPRAISAL_DATE,
     src.LAST_INTEREST_APPLIED_DATE,
     src.LAST_MODIFIED_DATE,
     src.LAST_SET_TO_ARREARS_DATE,
     src.LATE_PAYMENTS_RECALCULATION_METHOD,
     src.LOAN_AMOUNT,
     src.LOAN_NAME,
     src.ORIGINAL_ACCOUNT_KEY,
     src.PAYMENT_METHOD,
     src.LOAN_PENALTY_CALCULATION_METHOD,
     src.PENALTY_RATE,
     src.APPLY_INTEREST_ON_PREPAYMENT_METHOD,
     src.PREPAYMENT_RECALCULATION_METHOD,
     src.PRODUCT_TYPE_KEY,
     src.RESCHEDULED_ACCOUNT_KEY,
     src.GRACE_PERIOD,
     src.GRACE_PERIOD_TYPE,
     src.HAS_CUSTOM_SCHEDULE,
     src.PAYMENT_PLAN,
     src.PERIODIC_PAYMENT,
     src.PRINCIPAL_REPAYMENT_INTERVAL,
     src.REPAYMENT_INSTALLMENTS,
     src.REPAYMENT_PERIOD_COUNT,
     src.REPAYMENT_PERIOD_UNIT,
     src.REPAYMENT_SCHEDULE_METHOD,
     src.SCHEDULE_DUE_DATES_METHOD,
     src.TRANCHES,
     src.LAST_INTEREST_REVIEW_DATE,
     src.CURRENCY_CODE,
	 CURRENT_TIMESTAMP
    );


CREATE OR REPLACE TASK LENDX_SANDBOX.LENDX_DW.FACT_LOAN_REPAYMENTS
WAREHOUSE = COMPUTE_WH
AFTER LENDX_SANDBOX.LENDX_DW.STG_LOAN_REPAYMENTS
AS 
MERGE INTO LENDX_SANDBOX.LENDX_DW.FACT_LOAN_REPAYMENTS AS tgt
USING LENDX_STG.STG_LOAN_REPAYMENTS AS src
ON (tgt.FACT_KEY = src.FACT_KEY)
WHEN MATCHED THEN
    UPDATE SET tgt.DUE_DATE = src.DUE_DATE,
               tgt.FEES_DUE = src.FEES_DUE,
               tgt.FEES_PAID = src.FEES_PAID,
               tgt.INTEREST_DUE = src.INTEREST_DUE,
               tgt.INTEREST_PAID = src.INTEREST_PAID,
               tgt.PARENT_ACCOUNT_KEY = src.PARENT_ACCOUNT_KEY,
               tgt.PENALTY_DUE = src.PENALTY_DUE,
               tgt.PENALTY_PAID = src.PENALTY_PAID,
               tgt.PRINCIPAL_DUE = src.PRINCIPAL_DUE,
               tgt.PRINCIPAL_PAID = src.PRINCIPAL_PAID,
               tgt.STATE = src.STATE,
               tgt.TAX_FEES_DUE = src.TAX_FEES_DUE,
               tgt.TAX_FEES_PAID = src.TAX_FEES_PAID,
               tgt.TAX_INTEREST_DUE = src.TAX_INTEREST_DUE,
               tgt.TAX_INTEREST_PAID = src.TAX_INTEREST_PAID,
               tgt.TAX_PENALTY_DUE = src.TAX_PENALTY_DUE,
               tgt.TAX_PENALTY_PAID = src.TAX_PENALTY_PAID,
               tgt.AUDIT_LAST_MODIFIED_DATE = CURRENT_TIMESTAMP
WHEN NOT MATCHED THEN
    INSERT
    (
        FACT_KEY,
        FACT_LOAN_ACCOUNTS_FK,
        DUE_DATE,
        ENCODED_KEY,
        FEES_DUE,
        FEES_PAID,
        INTEREST_DUE,
        INTEREST_PAID,
        PARENT_ACCOUNT_KEY,
        PENALTY_DUE,
        PENALTY_PAID,
        PRINCIPAL_DUE,
        PRINCIPAL_PAID,
        STATE,
        TAX_FEES_DUE,
        TAX_FEES_PAID,
        TAX_INTEREST_DUE,
        TAX_INTEREST_PAID,
        TAX_PENALTY_DUE,
        TAX_PENALTY_PAID,
        AUDIT_LOADED_DATE
    )
    VALUES
    (MD5(src.ENCODED_KEY),
     src.FACT_LOAN_ACCOUNTS_FK,
     src.DUE_DATE,
     src.ENCODED_KEY,
     src.FEES_DUE,
     src.FEES_PAID,
     src.INTEREST_DUE,
     src.INTEREST_PAID,
     src.PARENT_ACCOUNT_KEY,
     src.PENALTY_DUE,
     src.PENALTY_PAID,
     src.PRINCIPAL_DUE,
     src.PRINCIPAL_PAID,
     src.STATE,
     src.TAX_FEES_DUE,
     src.TAX_FEES_PAID,
     src.TAX_INTEREST_DUE,
     src.TAX_INTEREST_PAID,
     src.TAX_PENALTY_DUE,
     src.TAX_PENALTY_PAID,
     CURRENT_TIMESTAMP
    );


CREATE OR REPLACE TASK LENDX_SANDBOX.LENDX_DW.FACT_REPAYMENTS_INSTALLMENTS
WAREHOUSE = COMPUTE_WH
AFTER LENDX_SANDBOX.LENDX_DW.FACT_LOAN_REPAYMENTS
AS
UPDATE LENDX_DW.FACT_LOAN_REPAYMENTS
SET FACT_LOAN_REPAYMENTS.INSTALLMENT_INTEREST_AMOUNT_DUE = STG_INSTALLMENTS.INSTALLMENT_INTEREST_AMOUNT_DUE,
    FACT_LOAN_REPAYMENTS.INSTALLMENT_INTEREST_AMOUNT_EXPECTED = STG_INSTALLMENTS.INSTALLMENT_INTEREST_AMOUNT_EXPECTED,
    FACT_LOAN_REPAYMENTS.INSTALLMENT_INTEREST_AMOUNT_PAID = STG_INSTALLMENTS.INSTALLMENT_INTEREST_AMOUNT_PAID,
    FACT_LOAN_REPAYMENTS.INSTALLMENT_INTEREST_TAX_DUE = STG_INSTALLMENTS.INSTALLMENT_INTEREST_TAX_DUE,
    FACT_LOAN_REPAYMENTS.INSTALLMENT_INTEREST_TAX_EXPECTED = STG_INSTALLMENTS.INSTALLMENT_INTEREST_TAX_EXPECTED,
    FACT_LOAN_REPAYMENTS.INSTALLMENT_INTEREST_TAX_PAID = STG_INSTALLMENTS.INSTALLMENT_INTEREST_TAX_PAID,
    FACT_LOAN_REPAYMENTS.INSTALLMENT_LAST_PAID_DATE = STG_INSTALLMENTS.INSTALLMENT_LAST_PAID_DATE,
    FACT_LOAN_REPAYMENTS.INSTALLMENT_NUMBER = STG_INSTALLMENTS.INSTALLMENT_NUMBER,
    FACT_LOAN_REPAYMENTS.INSTALLMENT_PENALTY_AMOUNT_DUE = STG_INSTALLMENTS.INSTALLMENT_PENALTY_AMOUNT_DUE,
    FACT_LOAN_REPAYMENTS.INSTALLMENT_PENALTY_AMOUNT_EXPECTED = STG_INSTALLMENTS.INSTALLMENT_PENALTY_AMOUNT_EXPECTED,
    FACT_LOAN_REPAYMENTS.INSTALLMENT_PENALTY_AMOUNT_PAID = STG_INSTALLMENTS.INSTALLMENT_PENALTY_AMOUNT_PAID,
    FACT_LOAN_REPAYMENTS.INSTALLMENT_PENALTY_TAX_DUE = STG_INSTALLMENTS.INSTALLMENT_PENALTY_TAX_DUE,
    FACT_LOAN_REPAYMENTS.INSTALLMENT_PENALTY_TAX_EXPECTED = STG_INSTALLMENTS.INSTALLMENT_PENALTY_TAX_EXPECTED,
    FACT_LOAN_REPAYMENTS.INSTALLMENT_PENALTY_TAX_PAID = STG_INSTALLMENTS.INSTALLMENT_PENALTY_TAX_PAID,
    FACT_LOAN_REPAYMENTS.INSTALLMENT_REPAID_DATE = STG_INSTALLMENTS.INSTALLMENT_REPAID_DATE,
    FACT_LOAN_REPAYMENTS.INSTALLMENT_STATE = STG_INSTALLMENTS.INSTALLMENT_STATE
FROM LENDX_STG.STG_INSTALLMENTS
WHERE FACT_LOAN_REPAYMENTS.ENCODED_KEY = STG_INSTALLMENTS.ENCODED_KEY;


CREATE OR REPLACE TASK LENDX_SANDBOX.LENDX_DW.FACT_LOAN_REPAYMENTS_HISTORY
WAREHOUSE = COMPUTE_WH
AFTER LENDX_SANDBOX.LENDX_DW.SET_REPAYMENTS_HISTORY_SEQ
AS 
	INSERT INTO LENDX_DW.FACT_LOAN_REPAYMENTS_HISTORY
		(	FACT_KEY,
			FACT_LOAN_ACCOUNTS_FK,
			DUE_DATE,
			ENCODED_KEY,
			FEES_DUE,
			FEES_PAID,
			INTEREST_DUE,
			INTEREST_PAID,
			PARENT_ACCOUNT_KEY,
			PENALTY_DUE,
			PENALTY_PAID,
			PRINCIPAL_DUE,
			PRINCIPAL_PAID,
			STATE,
			TAX_FEES_DUE,
			TAX_FEES_PAID,
			TAX_INTEREST_DUE,
			TAX_INTEREST_PAID,
			TAX_PENALTY_DUE,
			TAX_PENALTY_PAID,
			SEQUENCE_NUMBER,
			AUDIT_LOADED_DATE
		)
		SELECT 
		 MD5(src.ENCODED_KEY),	
		 src.FACT_LOAN_ACCOUNTS_FK,
		 src.DUE_DATE,
		 src.ENCODED_KEY,
		 src.FEES_DUE,
		 src.FEES_PAID,
		 src.INTEREST_DUE,
		 src.INTEREST_PAID,
		 src.PARENT_ACCOUNT_KEY,
		 src.PENALTY_DUE,
		 src.PENALTY_PAID,
		 src.PRINCIPAL_DUE,
		 src.PRINCIPAL_PAID,
		 src.STATE,
		 src.TAX_FEES_DUE,
		 src.TAX_FEES_PAID,
		 src.TAX_INTEREST_DUE,
		 src.TAX_INTEREST_PAID,
		 src.TAX_PENALTY_DUE,
		 src.TAX_PENALTY_PAID ,
		 src.SEQUENCE_NUMBER,
		 CURRENT_TIMESTAMP
		FROM LENDX_SANDBOX.LENDX_STG.STG_LOAN_REPAYMENTS_HISTORY src

	

CREATE OR REPLACE TASK LENDX_SANDBOX.LENDX_DW.FACT_REPAYMENTS_INSTALLMENTS_HISTORY
WAREHOUSE = COMPUTE_WH
AFTER LENDX_SANDBOX.LENDX_DW.FACT_REPAYMENTS_INSTALLMENTS
AS
UPDATE LENDX_DW.FACT_LOAN_REPAYMENTS_HISTORY
SET FACT_LOAN_REPAYMENTS_HISTORY.INSTALLMENT_INTEREST_AMOUNT_DUE = FACT_LOAN_REPAYMENTS.INSTALLMENT_INTEREST_AMOUNT_DUE,
    FACT_LOAN_REPAYMENTS_HISTORY.INSTALLMENT_INTEREST_AMOUNT_EXPECTED = FACT_LOAN_REPAYMENTS.INSTALLMENT_INTEREST_AMOUNT_EXPECTED,
    FACT_LOAN_REPAYMENTS_HISTORY.INSTALLMENT_INTEREST_AMOUNT_PAID = FACT_LOAN_REPAYMENTS.INSTALLMENT_INTEREST_AMOUNT_PAID,
    FACT_LOAN_REPAYMENTS_HISTORY.INSTALLMENT_INTEREST_TAX_DUE = FACT_LOAN_REPAYMENTS.INSTALLMENT_INTEREST_TAX_DUE,
    FACT_LOAN_REPAYMENTS_HISTORY.INSTALLMENT_INTEREST_TAX_EXPECTED = FACT_LOAN_REPAYMENTS.INSTALLMENT_INTEREST_TAX_EXPECTED,
    FACT_LOAN_REPAYMENTS_HISTORY.INSTALLMENT_INTEREST_TAX_PAID = FACT_LOAN_REPAYMENTS.INSTALLMENT_INTEREST_TAX_PAID,
    FACT_LOAN_REPAYMENTS_HISTORY.INSTALLMENT_LAST_PAID_DATE = FACT_LOAN_REPAYMENTS.INSTALLMENT_LAST_PAID_DATE,
    FACT_LOAN_REPAYMENTS_HISTORY.INSTALLMENT_NUMBER = FACT_LOAN_REPAYMENTS.INSTALLMENT_NUMBER,
    FACT_LOAN_REPAYMENTS_HISTORY.INSTALLMENT_PENALTY_AMOUNT_DUE = FACT_LOAN_REPAYMENTS.INSTALLMENT_PENALTY_AMOUNT_DUE,
    FACT_LOAN_REPAYMENTS_HISTORY.INSTALLMENT_PENALTY_AMOUNT_EXPECTED = FACT_LOAN_REPAYMENTS.INSTALLMENT_PENALTY_AMOUNT_EXPECTED,
    FACT_LOAN_REPAYMENTS_HISTORY.INSTALLMENT_PENALTY_AMOUNT_PAID = FACT_LOAN_REPAYMENTS.INSTALLMENT_PENALTY_AMOUNT_PAID,
    FACT_LOAN_REPAYMENTS_HISTORY.INSTALLMENT_PENALTY_TAX_DUE = FACT_LOAN_REPAYMENTS.INSTALLMENT_PENALTY_TAX_DUE,
    FACT_LOAN_REPAYMENTS_HISTORY.INSTALLMENT_PENALTY_TAX_EXPECTED = FACT_LOAN_REPAYMENTS.INSTALLMENT_PENALTY_TAX_EXPECTED,
    FACT_LOAN_REPAYMENTS_HISTORY.INSTALLMENT_PENALTY_TAX_PAID = FACT_LOAN_REPAYMENTS.INSTALLMENT_PENALTY_TAX_PAID,
    FACT_LOAN_REPAYMENTS_HISTORY.INSTALLMENT_REPAID_DATE = FACT_LOAN_REPAYMENTS.INSTALLMENT_REPAID_DATE,
    FACT_LOAN_REPAYMENTS_HISTORY.INSTALLMENT_STATE = FACT_LOAN_REPAYMENTS.INSTALLMENT_STATE
FROM LENDX_DW.FACT_LOAN_REPAYMENTS
WHERE FACT_LOAN_REPAYMENTS_HISTORY.ENCODED_KEY = FACT_LOAN_REPAYMENTS.ENCODED_KEY
AND FACT_LOAN_REPAYMENTS_HISTORY.SEQUENCE_NUMBER = LENDX_SANDBOX.LENDX_DW.GET_REPAYMENT_CURRENT_SEQUENCE_NUMBER(FACT_LOAN_REPAYMENTS.PARENT_ACCOUNT_KEY);


ALTER task LENDX_SANDBOX.LENDX_DW.DIM_ORIGINATOR RESUME;
ALTER task LENDX_SANDBOX.LENDX_DW.DIM_BORROWER RESUME;
ALTER task LENDX_SANDBOX.LENDX_DW.DIM_LOAN_PRODUCT RESUME;
ALTER task LENDX_SANDBOX.LENDX_DW.FACT_LOAN_ACCOUNTS RESUME;
ALTER task LENDX_SANDBOX.LENDX_DW.FACT_LOAN_REPAYMENTS RESUME;
ALTER task LENDX_SANDBOX.LENDX_DW.FACT_REPAYMENTS_INSTALLMENTS RESUME;
ALTER task LENDX_SANDBOX.LENDX_DW.FACT_LOAN_REPAYMENTS_HISTORY RESUME;
ALTER task LENDX_SANDBOX.LENDX_DW.FACT_REPAYMENTS_INSTALLMENTS_HISTORY RESUME;

--** AFTER DW LOAD EXECUTIONS -> Clean the Staging area.

CREATE OR REPLACE TASK LENDX_SANDBOX.LENDX_DW.TRUNC_STG_ORIGINATOR
WAREHOUSE = COMPUTE_WH
AFTER LENDX_SANDBOX.LENDX_DW.DIM_ORIGINATOR
AS
TRUNCATE TABLE LENDX_SANDBOX.LENDX_STG.STG_ORIGINATOR;


CREATE OR REPLACE TASK LENDX_SANDBOX.LENDX_DW.TRUNC_STG_BORROWER
WAREHOUSE = COMPUTE_WH
AFTER LENDX_SANDBOX.LENDX_DW.DIM_BORROWER
AS
TRUNCATE TABLE LENDX_SANDBOX.LENDX_STG.STG_BORROWER;


CREATE OR REPLACE TASK LENDX_SANDBOX.LENDX_DW.TRUNC_STG_LOAN_PRODUCT
WAREHOUSE = COMPUTE_WH
AFTER LENDX_SANDBOX.LENDX_DW.DIM_LOAN_PRODUCT
AS
TRUNCATE TABLE LENDX_SANDBOX.LENDX_STG.STG_LOAN_PRODUCT;


CREATE OR REPLACE TASK LENDX_SANDBOX.LENDX_DW.TRUNC_STG_LOAN_ACCOUNTS
WAREHOUSE = COMPUTE_WH
AFTER LENDX_SANDBOX.LENDX_DW.FACT_LOAN_ACCOUNTS
AS
TRUNCATE TABLE LENDX_SANDBOX.LENDX_STG.STG_LOAN_ACCOUNTS;


CREATE OR REPLACE TASK LENDX_SANDBOX.LENDX_DW.TRUNC_STG_LOAN_REPAYMENTS
WAREHOUSE = COMPUTE_WH
AFTER LENDX_SANDBOX.LENDX_DW.FACT_LOAN_REPAYMENTS
AS
TRUNCATE TABLE LENDX_SANDBOX.LENDX_STG.STG_LOAN_REPAYMENTS;


CREATE OR REPLACE TASK LENDX_SANDBOX.LENDX_DW.TRUNC_STG_INSTALLMENTS
WAREHOUSE = COMPUTE_WH
AFTER LENDX_SANDBOX.LENDX_DW.FACT_REPAYMENTS_INSTALLMENTS
AS
TRUNCATE TABLE LENDX_SANDBOX.LENDX_STG.STG_INSTALLMENTS;


CREATE OR REPLACE TASK LENDX_SANDBOX.LENDX_DW.TRUNC_STG_LOAN_REPAYMENTS_HISTORY
WAREHOUSE = COMPUTE_WH
AFTER LENDX_SANDBOX.LENDX_DW.FACT_LOAN_REPAYMENTS_HISTORY
AS
TRUNCATE TABLE LENDX_SANDBOX.LENDX_STG.STG_LOAN_REPAYMENTS_HISTORY;


ALTER task LENDX_SANDBOX.LENDX_DW.TRUNC_STG_ORIGINATOR RESUME;
ALTER task LENDX_SANDBOX.LENDX_DW.TRUNC_STG_BORROWER RESUME;
ALTER task LENDX_SANDBOX.LENDX_DW.TRUNC_STG_LOAN_PRODUCT RESUME;
ALTER task LENDX_SANDBOX.LENDX_DW.TRUNC_STG_LOAN_ACCOUNTS RESUME;
ALTER task LENDX_SANDBOX.LENDX_DW.TRUNC_STG_LOAN_REPAYMENTS RESUME;
ALTER task LENDX_SANDBOX.LENDX_DW.TRUNC_STG_INSTALLMENTS RESUME;