-- Insert default value for dimension key missmatch
INSERT INTO LENDX_SANDBOX.LENDX_DW.DIM_ORIGINATOR
(
    DIMENSION_KEY,
    CREATION_DATE,
    ENCODED_KEY,
    ID,
    NAME,
    NOTES,
    AUDIT_LOADED_DATE
)
VALUES
('NotFoundValue',
 CURRENT_TIMESTAMP,
 'NotFoundValue',
 'NotFoundValue',
 'Not Found Value',
 'Originator Key Not Found',
 CURRENT_TIMESTAMP
)

INSERT INTO LENDX_SANDBOX.LENDX_DW.DIM_BORROWER
(
    DIMENSION_KEY,
    CREATION_DATE,
    ENCODED_KEY,
    ID,
    LAST_NAME,
    NOTES,
    AUDIT_LOADED_DATE
)
VALUES
('NotFoundValue',
 CURRENT_TIMESTAMP,
 'NotFoundValue',
 'NotFoundValue',
 'Not Found Value',
 'Originator Key Not Found',
 CURRENT_TIMESTAMP
)

INSERT INTO LENDX_SANDBOX.LENDX_DW.DIM_LOAN_PRODUCT
(
    DIMENSION_KEY,
    CREATION_DATE,
    ENCODED_KEY,
    ID,
    PRODUCT_NAME,
    PRODUCT_DESCRIPTION,
    AUDIT_LOADED_DATE
)
VALUES
('NotFoundValue',
 CURRENT_TIMESTAMP,
 'NotFoundValue',
 'NotFoundValue',
 'Not Found Value',
 'Originator Key Not Found',
 CURRENT_TIMESTAMP
)

-- insert a default value for time
INSERT INTO LENDX_SANDBOX.LENDX_DW.DIM_TIME
(
    DIMENSION_KEY,
    CALENDARDATE,
    CALENDARDATESTRING,
    CALENDARDATEALT,
    CALENDARYEAR,
    CALENDARYEARDESC,
    CALENDARQUARTER,
    CALENDARQUARTERDESC,
    CALENDARQUARTERYEAR,
    MONTHNUMBEROFYEAR,
    MONTHYEAR,
    MONTHNAME,
    MONTHYEARDESC,
    MONTHYEARALT,
    DAYNUMBEROFMONTH,
    NUMBEROFDAYSINMONTH,
    DAYNUMBEROFYEAR,
    WEEKNUMBERYEAR,
    WEEKYEAR,
    ISOWEEKNUMBEROFYEAR,
    ISOWEEKYEAR,
    WEEKDAY,
    WEEKDAYNAME,
    ISWEEKDAYFLAG,
    ISWEEKDAYDESC
)
VALUES
(10000101, '1000-01-01', 'NoData', '', 0, '', 0, '', 0, 0, 0, '', '', '', 0, 0, 0, 0, 0, 0, 0, 0, '', 0, '');